// Guards the surfaces this repo publishes against the placeholder domain.
//
// `worth.example` is the fixture origin the other test files pass as SITE_URL.
// It is fine inside tests and inside the preview-only fallbacks of the build
// scripts (previews are noindex and ship no discovery files). It is not fine in
// anything that is shipped or indexed as-is:
//
//   public/**          copied verbatim into dist/ and served from the live site
//   articles/**        markdown mirrors indexed on github.com, each linking back
//   .github/FUNDING.yml rendered by GitHub as the repository's Sponsor button
//
// Before this test, 563 tracked references pointed at the placeholder: all 40
// mirrors' "Live" links, /api/articles.json on the live site, the sitemap-extra
// twin list and the Sponsor button. Every one of them was a dead link.
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const root = path.join(__dirname, '..');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const SITE = String(pkg.homepage || '').replace(/\/+$/, '');
const PLACEHOLDER = /worth\.example/;

// Generated by scripts/generate-seo.mjs into public/ (gitignored). The other
// test files regenerate them with the fixture origin, so they are excluded here.
const GENERATED_IN_PUBLIC = new Set(['robots.txt', 'sitemap.xml', 'feed.xml', 'llms.txt', 'ai.txt']);

function walk(dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

function publishedFiles() {
  const files = [];
  for (const f of walk(path.join(root, 'public'))) {
    if (path.dirname(f) === path.join(root, 'public') && GENERATED_IN_PUBLIC.has(path.basename(f))) continue;
    if (/\.(png|jpg|jpeg|webp|gif|ico|woff2?)$/i.test(f)) continue;
    files.push(f);
  }
  for (const f of walk(path.join(root, 'articles'))) if (f.endsWith('.md')) files.push(f);
  files.push(path.join(root, '.github', 'FUNDING.yml'));
  return files;
}

function mirrors() {
  return fs.readdirSync(path.join(root, 'articles'))
    .filter((f) => f.endsWith('.md') && f !== 'README.md')
    .sort()
    .map((f) => path.join(root, 'articles', f));
}

function publishedRoutes() {
  // The tracked root sitemap is the repo's own statement of which URLs exist.
  const xml = fs.readFileSync(path.join(root, 'sitemap.xml'), 'utf8');
  return new Set([...xml.matchAll(/<loc>(.*?)<\/loc>/g)].map((m) => m[1]));
}

test('package.json homepage is the live origin the published files link to', () => {
  assert.match(SITE, /^https:\/\/[^/]+/, 'package.json "homepage" must be an https URL');
  assert.doesNotMatch(SITE, PLACEHOLDER, 'package.json "homepage" is still the placeholder');
  assert.ok(publishedRoutes().has(SITE + '/'), `tracked sitemap.xml does not list the homepage ${SITE}/`);
});

test('nothing the repo publishes references the placeholder domain', () => {
  const offenders = [];
  for (const file of publishedFiles()) {
    const text = fs.readFileSync(file, 'utf8');
    const hits = text.split('\n').reduce((n, line) => n + (PLACEHOLDER.test(line) ? 1 : 0), 0);
    if (hits) offenders.push(`${path.relative(root, file)} (${hits} line${hits === 1 ? '' : 's'})`);
  }
  assert.deepEqual(offenders, [], 'placeholder domain in published files:\n  ' + offenders.join('\n  '));
});

test('every markdown mirror links back to a route the site actually publishes', () => {
  const routes = publishedRoutes();
  const files = mirrors();
  assert.equal(files.length, 40, 'expected the 40 markdown mirrors');
  for (const file of files) {
    const text = fs.readFileSync(file, 'utf8');
    const m = text.match(/^live_url: "([^"]+)"$/m);
    assert.ok(m, `${path.basename(file)}: missing live_url front matter`);
    assert.ok(m[1].startsWith(SITE + '/'), `${path.basename(file)}: live_url ${m[1]} is not under ${SITE}/`);
    assert.ok(routes.has(m[1]), `${path.basename(file)}: live_url ${m[1]} is not in sitemap.xml`);
    assert.ok(text.includes(`**Live Calculator:** [${m[1]}](${m[1]})`), `${path.basename(file)}: body "Live Calculator" link does not match live_url`);
    for (const link of text.matchAll(/\]\((https?:\/\/[^)]+)\)/g)) {
      const url = link[1];
      if (!url.startsWith(SITE)) continue;
      assert.ok(routes.has(url), `${path.basename(file)}: links to ${url}, which is not in sitemap.xml`);
    }
  }
});

test('public/api/articles.json points every entry at its live route', () => {
  const routes = publishedRoutes();
  const entries = JSON.parse(fs.readFileSync(path.join(root, 'public', 'api', 'articles.json'), 'utf8'));
  assert.ok(Array.isArray(entries) && entries.length >= 46, `expected at least 46 entries, got ${entries.length}`);
  for (const entry of entries) {
    assert.equal(entry.url, `${SITE}/${entry.slug}/`, `${entry.slug}: url does not match slug under the live origin`);
    assert.ok(routes.has(entry.url), `${entry.slug}: ${entry.url} is not in sitemap.xml`);
  }
});

test('the committed markdown mirrors are exactly what the generator produces', () => {
  const before = new Map(mirrors().map((f) => [f, fs.readFileSync(f, 'utf8')]));
  execFileSync(process.execPath, ['scripts/generate-articles-md.mjs'], { cwd: root, stdio: 'pipe' });
  const stale = [];
  for (const f of mirrors()) {
    if (before.get(f) !== fs.readFileSync(f, 'utf8')) stale.push(path.relative(root, f));
  }
  assert.deepEqual(stale, [], 'mirrors out of date with scripts/generate-articles-md.mjs - commit the regenerated files:\n  ' + stale.join('\n  '));
});

test('the mirror generator refuses to run against a placeholder homepage', () => {
  const dir = fs.mkdtempSync(path.join(require('node:os').tmpdir(), 'worth-mirrors-'));
  try {
    fs.mkdirSync(path.join(dir, 'scripts'));
    fs.mkdirSync(path.join(dir, 'articles'));
    fs.copyFileSync(path.join(root, 'scripts', 'generate-articles-md.mjs'), path.join(dir, 'scripts', 'generate-articles-md.mjs'));
    fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({ ...pkg, homepage: 'https://worth.example/' }));
    assert.throws(
      () => execFileSync(process.execPath, ['scripts/generate-articles-md.mjs'], { cwd: dir, stdio: 'pipe' }),
      /homepage/,
    );
    assert.equal(fs.readdirSync(path.join(dir, 'articles')).length, 0, 'generator must not write mirrors for a placeholder origin');
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});
