/**
 * Eighteen additional calculator pages, chosen for search demand that the site
 * did not answer: the everyday arithmetic people type into a search box —
 * splitting a bill, taking tax off a total, comparing two package sizes,
 * working out what a 401(k) becomes, what a pet costs over its life.
 *
 * House rules match cluster-content.mjs: a unique title (<= 60 characters), a
 * unique description (<= 155), a real formula, a worked-example table that is
 * not shared with any other page, three explanatory notes and two or more FAQs
 * that the page itself answers.
 *
 * Every route here has a matching engine in calculator-engines.mjs, so the page
 * ships a working calculator rather than a screenshot of one.
 */

const H = 'https://github.com/njohn931d-dotcom/bbbh';

/** @typedef {import('./cluster-content.mjs').ClusterEntry} ClusterEntry */

/** @type {ClusterEntry[]} */
export const SUITE_CONTENT = [
  {
    route: 'calculators/tip-calculator',
    h1: 'Tip Calculator: Tip, Total and Split per Person',
    title: 'Tip Calculator: Tip, Total and Split per Person',
    desc: 'Work out the tip on the pre-tax bill, the total to pay, and what each person owes when you split it. Free, no sign-up, runs in your browser.',
    intent: 'tool',
    intro: 'Enter the bill, the tip you want to leave and how many people are paying, and see the tip, the total and each person’s share.',
    formula: { name: 'Tip and split', expr: 'tip = pre-tax subtotal × tip%', plain: 'The pre-tax subtotal is the bill divided by 1 + tax rate. Tipping on the post-tax total quietly raises the tip by the tax rate.' },
    assumptions: 'An $86 bill with 8% sales tax, an 18% tip, split between two people.',
    caveat: 'Tipping norms vary by country and by venue, and in many places service is already included. Check the receipt before adding a percentage on top of a charge that is already there.',
    table: {
      head: ['Tip', 'On a $86 bill', 'Total', 'Each of two'],
      rows: [['10%', '$7.93', '$93.93', '$46.97'], ['15%', '$11.90', '$97.90', '$48.95'], ['18%', '$14.27', '$100.27', '$50.14'], ['20%', '$15.85', '$101.85', '$50.93'], ['25%', '$19.82', '$105.82', '$52.91']],
    },
    notes: [
      'A percentage applies to the food and drink, not to the tax the restaurant is collecting on behalf of the state. On an 8% tax rate, tipping on the post-tax total adds about 1.4 percentage points to the tip you thought you left.',
      'Splitting unevenly is the part that causes friction. Anything that makes the shares visible before the card arrives — including who had the extra drink — removes the argument at the table.',
      'Rounding the total to the nearest dollar is worth about fifty cents and removes the need for change. Rounding up to the next $5 is a different decision, and the calculator shows both.',
    ],
    faqs: [
      ['Should I tip on the pre-tax or post-tax amount?', 'The pre-tax subtotal is the usual convention and the fairer one, because the tax is not the server’s to earn. In practice most people tip on the printed total and pay slightly over the intended percentage.'],
      ['How much should I tip?', 'Fifteen to twenty per cent is the common range for table service in the United States, with twenty becoming the informal default in cities. Buffets, takeaway and counter service are usually lower or nothing.'],
      ['Does the calculator work for a large group?', 'Yes. Enter the party size and every figure is divided evenly. Groups of six or more sometimes have an automatic service charge added, in which case check the receipt and set the tip to zero rather than paying twice.'],
    ],
    links: ['calculators/cost-of-time', 'calculators/50-30-20-budget-calculator', 'calculators/sales-tax-calculator', 'calculators/unit-price-calculator'],
    related: ['calculators/percent-off-calculator', 'guides/small-purchases', 'calculators/daily-savings', 'articles/spending-decisions/seven-questions-before-a-big-purchase'],
  },
  {
    route: 'calculators/sales-tax-calculator',
    h1: 'Sales Tax Calculator: Add or Remove Tax',
    title: 'Sales Tax Calculator: Add or Remove Tax',
    desc: 'Add sales tax to a price, or take it back out of a total to find the amount before tax. Works for any rate, including no-tax states and VAT.',
    intent: 'tool',
    intro: 'Enter an amount and a rate to add tax, or switch the mode to work backwards from a total that already includes tax.',
    formula: { name: 'Adding and removing tax', expr: 'with tax = net × (1 + rate);  net = total ÷ (1 + rate)', plain: 'Removing tax means dividing by 1 + rate, not multiplying by the rate. The two are close on a receipt and diverge quickly over a year of expenses.' },
    assumptions: 'A $1,299 purchase at an 8.25% combined state and local rate.',
    caveat: 'Rates differ by state, county and city, and many places exempt food, clothing or medicine. The rate on your receipt is the one that applies, not the state headline.',
    table: {
      head: ['Rate', 'Net price', 'Tax', 'Total'],
      rows: [['5.00%', '$1,299.00', '$64.95', '$1,363.95'], ['6.50%', '$1,299.00', '$84.44', '$1,383.44'], ['8.25%', '$1,299.00', '$107.17', '$1,406.17'], ['10.00%', '$1,299.00', '$129.90', '$1,428.90'], ['12.00%', '$1,299.00', '$155.88', '$1,454.88']],
    },
    notes: [
      'Twenty dollars of every hundred dollars spent in a 20% VAT jurisdiction is tax, not goods. Working backwards from the total is the only way to see the proportion, which is why every business expense claim needs the net figure.',
      'Sales tax is charged at the point of sale and applies to almost everything for a final consumer. A business buying the same item for resale usually presents a certificate and pays nothing.',
      'The rate on a receipt is often several rates added together — state, county, city and sometimes a transport district. When you need the exact figure for a return, use the combined rate from the receipt rather than the state rate.',
    ],
    faqs: [
      ['How do I remove sales tax from a total?', 'Divide the total by 1 plus the rate as a decimal. At 8.25%, divide by 1.0825. Multiplying the total by 0.0825 and subtracting gives a slightly different, wrong answer.'],
      ['Which states have no sales tax?', 'Delaware, Montana, New Hampshire and Oregon have no statewide sales tax, and Alaska has none at state level though local rates exist. Local rates also apply elsewhere in ways the state rate alone does not capture.'],
      ['Is sales tax the same as VAT?', 'Both are consumption taxes charged on the final buyer, but VAT is collected at each stage of production with businesses reclaiming what they paid. That is why a VAT receipt shows the tax separately by law, and a US sales tax receipt often does not.'],
    ],
    links: ['calculators/percent-off-calculator', 'calculators/trump-tariff-calculator-2026', 'calculators/cost-of-time', 'calculators/unit-price-calculator'],
    related: ['calculators/profit-margin-calculator', 'calculators/tip-calculator', 'articles/spending-decisions/cost-per-use-how-to-compare-purchases', 'calculators/inflation-calculator-2026'],
  },
  {
    route: 'calculators/percent-off-calculator',
    h1: 'Percent Off Calculator: Stacked Discounts and Final Price',
    title: 'Percent Off Calculator: Stacked Discounts',
    desc: 'See what a discount leaves you paying, including two discounts stacked on the same item — which multiply rather than add, and save less than they look.',
    intent: 'tool',
    intro: 'Enter a price and one or two discounts to see the real final price, the effective discount and the gap between the two.',
    formula: { name: 'Stacked discounts', expr: 'final = price × (1 − d₁) × (1 − d₂)', plain: 'Two discounts applied in sequence multiply. Thirty per cent then twenty per cent is 44% off, not 50%, because the second discount applies to the already-reduced price.' },
    assumptions: 'A $180 item with 30% off, then a further 20% off at the till.',
    caveat: 'A discount is only a saving if the item was going to be bought at full price. A 50% reduction on something you did not need is still money spent.',
    table: {
      head: ['Original price', 'After 30% off', 'After a further 20%', 'Effective discount'],
      rows: [['$100', '$70.00', '$56.00', '44.0%'], ['$180', '$126.00', '$100.80', '44.0%'], ['$300', '$210.00', '$168.00', '44.0%'], ['$1,000', '$700.00', '$560.00', '44.0%']],
    },
    notes: [
      'Adding the percentages always flatters the discount. The gap widens with the size of the second discount: 50% then 50% is 75% off, and 30% then 30% is 51%.',
      'The order does not matter. Taking 20% off then 30% off gives exactly the same final price, which is worth knowing when a cashier offers the larger discount first.',
      'Store credit and gift cards change the arithmetic in a way calculators often miss: if the purchase is paid for partly with a card bought at a discount, the effective saving is higher than the headline percentage.',
    ],
    faqs: [
      ['Do stacked discounts add together?', 'No, they multiply. Twenty per cent off and then thirty per cent off is 44% off the original price, because the second discount is calculated on the reduced price rather than the original one.'],
      ['Which is better, 30% off then 20%, or 20% off then 30%?', 'They produce exactly the same final price. Multiplication is commutative, so the order of two percentage reductions never changes the result.'],
      ['How do I work out the original price from a discounted one?', 'Divide the discounted price by 1 minus the discount rate. A $56 price after a 30% discount came from $56 ÷ 0.7, or $80. Adding 30% back to $56 gives $72.80, which is wrong.'],
    ],
    links: ['calculators/sales-tax-calculator', 'calculators/unit-price-calculator', 'calculators/cost-per-use', 'calculators/cost-of-time'],
    related: ['guides/stop-impulse-buying', 'guides/30-day-rule-spending', 'calculators/daily-savings', 'articles/spending-decisions/why-you-impulse-spend-and-how-to-stop'],
  },
  {
    route: 'calculators/debt-snowball-vs-avalanche-calculator',
    h1: 'Debt Snowball vs Avalanche Calculator',
    title: 'Debt Snowball vs Avalanche Calculator',
    desc: 'Compare the snowball and avalanche debt payoff methods on your own balances: months to clear, total interest and what the choice actually costs.',
    intent: 'tool',
    intro: 'Enter two debts and the monthly amount you can pay, and see which order clears them faster and cheaper.',
    formula: { name: 'Two strategies', expr: 'avalanche: highest rate first;  snowball: smallest balance first', plain: 'Both pay the minimum on everything and throw every spare dollar at one target debt. Avalanche targets the highest interest rate, snowball targets the smallest balance.' },
    assumptions: 'A $1,800 balance at 19.99% and a $9,000 balance at 24.99%, with $600 a month to put towards them.',
    caveat: 'Both strategies assume the payment never drops and no new borrowing happens. A single new card balance resets the arithmetic, which is why closing the source matters more than picking the order.',
    table: {
      head: ['Paid a month', 'Avalanche interest', 'Snowball interest', 'Cost of the choice'],
      rows: [['$300', '$8,250', '$9,210', '$960'], ['$450', '$3,965', '$4,279', '$314'], ['$600', '$2,662', '$2,848', '$186'], ['$900', '$1,639', '$1,740', '$101']],
    },
    notes: [
      'Avalanche always costs less, and the gap is usually smaller than people expect because both strategies pay the same total each month. The column above shows the price of choosing momentum over arithmetic, and it falls as the payment rises.',
      'Snowball clears an individual debt sooner, which is what makes it work for people who need visible progress. The last column of the table is the price of that motivation, and paying it is a legitimate choice.',
      'The strategy matters far less than the payment. Raising $600 to $750 cuts the time and the interest dramatically; rearranging $600 does not.',
    ],
    faqs: [
      ['Which is better, snowball or avalanche?', 'Avalanche costs less and snowball feels better. If you have never cleared a balance before, the small win from snowball is often what keeps the plan alive, and the extra interest is usually a few tens of dollars.'],
      ['Does the snowball method hurt my credit score?', 'Clearing a balance does not hurt it, and reducing the number of accounts with balances usually helps. Closing the accounts afterwards can hurt, because it cuts your available credit and your average account age.'],
      ['What if I can only afford the minimum payments?', 'Then neither strategy has anything to allocate. The minimum payment covers interest and a little principal, so the balance falls slowly. Any plan that frees up even $50 a month makes both strategies work.'],
    ],
    links: ['calculators/credit-card-payoff-calculator-2026', 'calculators/loan-comparison-calculator-2026', 'calculators/student-loan-calculator-2026', 'calculators/emergency-fund-calculator'],
    related: ['calculators/net-worth-calculator-2026', 'calculators/savings-goal-calculator-2026', 'articles/saving-habits/how-to-save-1000-dollars-fast', 'calculators/after-tax-income'],
  },
  {
    route: 'calculators/rent-affordability-calculator',
    h1: 'How Much Rent Can I Afford? Calculator',
    title: 'How Much Rent Can I Afford? Calculator',
    desc: 'Apply the 25%, 30% and 40% rent-to-income rules to your own pay, then see what other debts leave you able to rent. Free and private.',
    intent: 'tool',
    intro: 'Enter your gross monthly income and existing debt payments to see the rent each rule allows and what is left over.',
    formula: { name: 'Rent-to-income', expr: 'max rent = gross monthly income × rule%', plain: 'Landlords commonly use 30% of gross income as the rent ceiling, with 40% as a hard limit in expensive markets. The rule is a screening device, not a budget.' },
    assumptions: 'A household earning $6,500 a month gross with $420 of other debt payments.',
    caveat: 'The 30% rule comes from public housing policy and applies to gross income, so it allows more than a take-home budget would. Landlords also check credit history and income stability, which no ratio captures.',
    table: {
      head: ['Income a month', '25%', '30%', '35%', '40%'],
      rows: [['$4,000', '$1,000', '$1,200', '$1,400', '$1,600'], ['$5,500', '$1,375', '$1,650', '$1,925', '$2,200'], ['$7,000', '$1,750', '$2,100', '$2,450', '$2,800'], ['$9,000', '$2,250', '$2,700', '$3,150', '$3,600'], ['$12,000', '$3,000', '$3,600', '$4,200', '$4,800']],
    },
    notes: [
      'The rule applies to gross income, which means the rent it allows is a larger share of what you actually take home. At a 25% effective tax rate, a 30%-of-gross rent is 40% of your net pay.',
      'Landing costs are separate from rent and are what usually break a budget: a deposit, the first month, a broker fee and sometimes the last month upfront can total three to four months of rent before you move in.',
      'Utilities, parking and building fees often sit outside the advertised rent. Adding them before applying the ratio is more honest than adding them afterwards and discovering the total is over the ceiling.',
    ],
    faqs: [
      ['What percentage of income should rent be?', 'Thirty per cent of gross income is the widely used benchmark, with 25% described as conservative and 40% as the point at which lenders and landlords start refusing. Some housing charities argue 30% is already too high for lower incomes.'],
      ['Should the rule use gross or net income?', 'Landlords use gross, because that is the figure they can verify. For your own budget, apply the same percentage to take-home pay: the rent you can actually carry is usually lower than the number a landlord approves.'],
      ['Do utilities count towards the 30% rule?', 'In the strict version of the rule, no, only rent. In practice most advisers count rent plus utilities and fees, because that is the amount that leaves your account each month.'],
    ],
    links: ['calculators/mortgage-calculator-2026', 'calculators/rent-vs-buy-calculator-2026', 'calculators/cost-of-living-calculator-2026', 'calculators/down-payment-calculator'],
    related: ['guides/how-much-house-can-i-afford-2026', 'calculators/after-tax-income', 'articles/spending-decisions/should-you-rent-or-buy', 'calculators/net-worth-calculator-2026'],
  },
  {
    route: 'calculators/gas-cost-calculator',
    h1: 'Gas Cost Calculator: Fuel for a Trip or a Month',
    title: 'Gas Cost Calculator: Fuel for a Trip',
    desc: 'Work out the fuel cost of a trip or a month of driving from distance, fuel economy and price per gallon — and what each passenger owes.',
    intent: 'tool',
    intro: 'Enter the distance, your car’s miles per gallon and the pump price to get the fuel bill, the gallons needed and the cost per mile.',
    formula: { name: 'Trip fuel cost', expr: 'gallons = miles ÷ mpg;  cost = gallons × price per gallon', plain: 'Distance divided by fuel economy gives the gallons burned. Multiply by the pump price for the cost of the fuel, which is not the whole cost of the journey.' },
    assumptions: 'A 320-mile trip driven twice at 28 mpg with fuel at $3.45 a gallon.',
    caveat: 'Fuel is roughly half the cost of running a car. A rate that covers wear, tyres, insurance and depreciation — the standard mileage rate — is the honest figure for anything beyond a one-off trip.',
    table: {
      head: ['Fuel economy', 'Gallons for 640 miles', 'Fuel cost', 'Cost per mile'],
      rows: [['18 mpg', '35.6', '$122.67', '$0.19'], ['24 mpg', '26.7', '$92.00', '$0.14'], ['32 mpg', '20.0', '$69.00', '$0.11'], ['45 mpg', '14.2', '$49.07', '$0.08'], ['60 mpg', '10.7', '$36.80', '$0.06']],
    },
    notes: [
      'Fuel economy falls sharply above about 60 mph, so the same journey costs more at motorway speeds than the official figure suggests. Air conditioning, roof racks and cold starts all take a further share.',
      'The gap between 18 and 32 mpg is nearly double the fuel cost for the same journey, which is why a fuel-efficient car pays for its premium fastest on long, regular journeys rather than short ones.',
      'Splitting the cost between passengers is a social decision the arithmetic does not settle: dividing fuel only is not the same as dividing the cost of the journey, and the difference is the wear and depreciation the driver absorbs.',
    ],
    faqs: [
      ['How do I calculate fuel cost per mile?', 'Divide the price of a gallon by the miles your car covers on it. At $3.45 a gallon and 28 mpg, fuel costs about 12 cents a mile. Adding wear and depreciation roughly doubles it.'],
      ['Is the trip cost only fuel?', 'No. Fuel is the visible part; tyres, servicing, insurance and depreciation accrue whether or not you notice them per trip. The standard mileage rate exists because the full cost is about twice the fuel bill.'],
      ['Why is my real mpg lower than the official figure?', 'Official figures come from a standardised test cycle. Short journeys, cold weather, air conditioning, roof racks and aggressive acceleration all reduce real-world economy, often by 15% to 25%.'],
    ],
    links: ['calculators/commute-cost', 'calculators/car-ownership-cost', 'calculators/car-loan-calculator-2026', 'calculators/electricity-cost-calculator'],
    related: ['calculators/depreciation-calculator-2026', 'guides/true-cost-of-car', 'articles/spending-decisions/true-cost-of-car-ownership', 'calculators/trump-tariff-calculator-2026'],
  },
  {
    route: 'calculators/unit-price-calculator',
    h1: 'Unit Price Calculator: Which Package Is Cheaper',
    title: 'Unit Price Calculator: Compare Package Prices',
    desc: 'Compare two package sizes by price per ounce, per item or per litre, see which is cheaper and what the difference is worth over a year.',
    intent: 'tool',
    intro: 'Enter the price and size of two options to compare them by unit price — the only fair way to compare two packages.',
    formula: { name: 'Unit price', expr: 'unit price = price ÷ size', plain: 'Divide the price by the quantity to get a cost per ounce, per item or per litre. The larger package is cheaper only if the unit price is lower, which is not always true.' },
    assumptions: 'A 12 oz jar at $4.50 against a 24 oz jar at $7.20, used four times a month.',
    caveat: 'A lower unit price only saves money if you finish the larger package before it spoils or you tire of it. Waste at the bottom of a container erases the saving entirely.',
    table: {
      head: ['Buying this much', 'Option A costs', 'Option B costs', 'Difference'],
      rows: [['12 oz', '$4.50', '$3.60', '$0.90'], ['24 oz', '$9.00', '$7.20', '$1.80'], ['48 oz', '$18.00', '$14.40', '$3.60'], ['96 oz', '$36.00', '$28.80', '$7.20']],
    },
    notes: [
      'Unit prices are quoted in different units on purpose. Comparing a price per sheet against a price per roll, or per 100 g against per ounce, defeats the comparison unless you convert first.',
      'The gap between the two options above is 20%, which is worth about $21 a year at four uses a month. On a single purchase the same saving is 90 cents, and that framing is why unit pricing works over time rather than per trip.',
      'Shrinkflation shows up here before it shows up anywhere else: the price stays the same and the size falls, so the unit price rises while the shelf price looks unchanged.',
    ],
    faqs: [
      ['How do I work out the unit price?', 'Divide the total price by the total quantity in the same unit. A 24 oz jar for $7.20 is 30 cents an ounce; a 12 oz jar for $4.50 is 37.5 cents an ounce, so the larger jar is cheaper.'],
      ['Is the bigger package always cheaper?', 'No. Larger packages are usually cheaper per unit but not universally, particularly when the smaller size is on promotion. The only way to know is to calculate the unit price for both.'],
      ['What units should I use?', 'Whatever the products share. If one is priced by weight and the other by volume, convert to a common measure first, otherwise the comparison is meaningless.'],
    ],
    links: ['calculators/percent-off-calculator', 'calculators/sales-tax-calculator', 'calculators/subscription-audit', 'calculators/subscription-cost'],
    related: ['calculators/daily-savings', 'calculators/inflation-calculator-2026', 'articles/saving-habits/sinking-funds-explained', 'guides/small-purchases'],
  },
  {
    route: 'calculators/50-30-20-budget-calculator',
    h1: '50/30/20 Budget Calculator',
    title: '50/30/20 Budget Calculator',
    desc: 'Split your take-home pay into needs, wants and savings with the 50/30/20 rule, and see how your actual rent and food spending compares.',
    intent: 'tool',
    intro: 'Enter your monthly take-home pay and your real housing and food costs to see whether the classic split is achievable or needs adjusting.',
    formula: { name: 'The 50/30/20 split', expr: 'needs = 50% · wants = 30% · savings = 20%', plain: 'Applied to take-home pay, half goes to essentials, a third to discretionary spending and a fifth to savings and debt repayment above the minimums.' },
    assumptions: 'A $4,200 monthly take-home income with $1,500 rent and $620 of food and essentials.',
    caveat: 'The split was popularised for households with stable incomes and moderate housing costs. In a high-cost city the needs line often exceeds half of take-home pay, and the honest response is a smaller wants line, not an unbalanced budget.',
    table: {
      head: ['Split', 'Needs', 'Wants', 'Savings'],
      rows: [['50/30/20', '$2,100', '$1,260', '$840'], ['60/20/20', '$2,520', '$840', '$840'], ['40/30/30', '$1,680', '$1,260', '$1,260'], ['70/10/20', '$2,940', '$420', '$840']],
    },
    notes: [
      'The percentages apply to take-home pay, not gross. Applying them to a gross salary inflates every line by the amount your employer withholds, which is the most common error with this rule.',
      'Housing is the line that decides everything. Above about 35% of take-home pay, the 50% needs bucket is spent before food, transport and utilities are counted, and the other two buckets have to shrink.',
      'Savings includes debt repayment above the minimum. Paying an extra $200 off a 24% credit card is a better return than any savings account, so it belongs in the same bucket even though it is not saving in the narrow sense.',
    ],
    faqs: [
      ['Is 50/30/20 a good budget?', 'It is a reasonable starting point and a poor rule. It works when housing is under a third of take-home pay and the income is stable; for renters in expensive cities, splitting needs and wants 60/20 usually describes reality better.'],
      ['Should I budget from gross or take-home pay?', 'Take-home pay, always. Budgeting from gross creates a plan for money you never receive, which is why those plans fail in the first month.'],
      ['Where does debt repayment fit?', 'Minimum payments belong in needs, because they are not optional. Anything above the minimum belongs in savings, because it improves your net worth exactly the way saving does.'],
    ],
    links: ['calculators/after-tax-income', 'calculators/rent-affordability-calculator', 'calculators/paycheck-breakdown', 'calculators/emergency-fund-calculator'],
    related: ['calculators/net-worth-calculator-2026', 'calculators/savings-goal-calculator-2026', 'articles/saving-habits/how-much-should-i-save-each-month', 'guides/hourly-budget'],
  },
  {
    route: 'calculators/profit-margin-calculator',
    h1: 'Profit Margin Calculator: Margin and Markup',
    title: 'Profit Margin Calculator: Margin and Markup',
    desc: 'Work out gross margin, net margin and markup from revenue and costs — and see why a 50% markup is only a 33% margin.',
    intent: 'tool',
    intro: 'Enter revenue, the cost of what you sold and your operating expenses to see gross margin, net margin and the markup on cost.',
    formula: { name: 'Margin and markup', expr: 'margin = (revenue − cost) ÷ revenue;  markup = (revenue − cost) ÷ cost', plain: 'Margin measures profit as a share of the selling price. Markup measures it as a share of the cost. The same profit is a smaller percentage of the larger number.' },
    assumptions: '$12,000 of revenue, $7,200 of cost of goods sold, $2,600 of operating expenses and 2.9% in payment fees.',
    caveat: 'Gross margin excludes fixed costs, so a healthy gross margin can coexist with a loss. Net margin is the figure that decides whether the business survives, and it depends on volume as much as price.',
    table: {
      head: ['Revenue', 'Gross margin', 'Net margin', 'Markup on cost'],
      rows: [['$1,000', '40.0%', '11.9%', '66.7%'], ['$5,000', '40.0%', '26.1%', '66.7%'], ['$12,000', '40.0%', '32.6%', '66.7%'], ['$50,000', '40.0%', '36.7%', '66.7%']],
    },
    notes: [
      'Fixed costs do not scale with revenue, which is why the net margin column improves as revenue rises even when the gross margin is identical. Profitability is a volume question as much as a pricing one.',
      'Payment fees and platform commissions belong in the cost of a sale, not in overhead. At 2.9% they cost $348 on the revenue above, which is more than many small businesses budget for software.',
      'Discounting cuts margin twice as fast as it cuts price. A 10% discount on a 40% margin product removes a quarter of the profit, which is why the recovery in volume has to be large to be worth it.',
    ],
    faqs: [
      ['What is the difference between margin and markup?', 'Markup is profit divided by cost; margin is profit divided by the selling price. A product bought for $60 and sold for $100 has a 40% margin and a 66.7% markup.'],
      ['What is a good profit margin?', 'It depends entirely on the industry. Grocery and retail run on single-digit net margins, software often exceeds 20%, and services sit between the two. Compare with your sector, not with a general benchmark.'],
      ['How do I calculate break-even revenue?', 'Divide fixed costs by the gross margin percentage. With $2,600 of overhead and a 40% gross margin, break-even is $6,500 of revenue — every dollar above that contributes profit.'],
    ],
    links: ['calculators/freelance-rate', 'calculators/freelance-rate-calculator-2026', 'calculators/roi-calculator', 'calculators/side-hustle-calculator-2026'],
    related: ['calculators/chatgpt-cost-calculator-2026', 'calculators/inflation-calculator-2026', 'guides/negotiate-hourly-rate', 'calculators/wage-growth-calculator-2026'],
  },
  {
    route: 'calculators/roi-calculator',
    h1: 'ROI Calculator: Return on Investment and Payback',
    title: 'ROI Calculator: Return on Investment',
    desc: 'Calculate ROI, the annualised return and the payback period for any investment, so a quick win and a slow one can be compared fairly.',
    intent: 'tool',
    intro: 'Enter what an investment cost, what it returned and how long it took to come back, and see the total return, the annualised return and the payback period.',
    formula: { name: 'ROI and CAGR', expr: 'ROI = (return − cost) ÷ cost;  CAGR = (return ÷ cost)^(1/years) − 1', plain: 'ROI is the total percentage gain over the whole period. The annualised figure spreads it across the years so investments of different lengths can be compared.' },
    assumptions: 'A $15,000 investment returning $22,400 over 18 months with $250 a month of ongoing return afterwards.',
    caveat: 'Neither figure accounts for risk, liquidity or the value of the time you put in. A 40% return on a business you worked in for free is not the same as 40% from an index fund.',
    table: {
      head: ['Months to realise', 'ROI', 'Annualised', 'Profit a month held'],
      rows: [['6', '49.33%', '128.43%', '$1,233.33'], ['12', '49.33%', '49.33%', '$616.67'], ['18', '49.33%', '30.72%', '$411.11'], ['36', '49.33%', '14.28%', '$205.56'], ['60', '49.33%', '8.35%', '$123.33']],
    },
    notes: [
      'A total return of 49% looks excellent until you see the holding period. Over five years it annualises to 8.35%, which is roughly what a broad index fund has historically delivered with far less risk.',
      'Payback period is the figure most small businesses actually use, because cash flow matters more than the percentage. Recovering the cost in eight months and then earning $250 a month is a different proposition from a paper gain.',
      'Costs left out of the calculation are the most common source of a wrong answer: platform fees, your own unpaid hours, taxes on the gain and the opportunity cost of the money while it was tied up.',
    ],
    faqs: [
      ['How do I calculate ROI?', 'Subtract the cost from the total return, then divide by the cost and multiply by 100. Spending $15,000 and receiving $22,400 is a profit of $7,400, or a 49.33% return.'],
      ['What is a good ROI?', 'There is no universal number, because it depends on risk and time. Annualising is the only fair comparison: a long-run stock market return is around 7% to 10% a year, and anything claiming far more deserves scrutiny.'],
      ['What is the difference between ROI and payback period?', 'ROI is a percentage gain; payback period is how long until the money is back. A project can have a high ROI and a long payback, which is a problem if you need the cash sooner.'],
    ],
    links: ['calculators/investment-return-calculator-2026', 'calculators/compound-interest-calculator', 'calculators/profit-margin-calculator', 'calculators/crypto-profit-calculator-2026'],
    related: ['calculators/apy-calculator', 'calculators/inflation-calculator-2026', 'articles/spending-decisions/lifestyle-creep-after-a-raise', 'calculators/401k-calculator'],
  },
  {
    route: 'calculators/bonus-tax-calculator',
    h1: 'Bonus Tax Calculator: What You Keep',
    title: 'Bonus Tax Calculator: What You Keep',
    desc: 'See what a bonus is worth after federal withholding, FICA, state tax and retirement contributions — and why the withheld amount is not the tax bill.',
    intent: 'tool',
    intro: 'Enter the bonus, how it is withheld and your state rate to see what reaches your account and the rate that was applied.',
    formula: { name: 'Supplemental withholding', expr: 'take-home = bonus − (federal + FICA + state + retirement)', plain: 'Bonuses are usually withheld at a flat supplemental rate of 22%, separate from the brackets used for regular pay, plus 7.65% of payroll tax.' },
    assumptions: 'An $8,000 bonus on a $72,000 salary, withheld at the 22% supplemental rate with a 5% state tax.',
    caveat: 'Withholding is a deposit against the year’s tax, not the tax itself. At the 32% marginal bracket, a 22% supplemental rate under-withholds and the difference arrives as a smaller refund or a balance due.',
    table: {
      head: ['Bonus', 'Withheld', 'Take-home', 'Effective rate'],
      rows: [['$1,000', '$345', '$655', '34.50%'], ['$5,000', '$1,722', '$3,278', '34.45%'], ['$10,000', '$3,445', '$6,555', '34.45%'], ['$25,000', '$8,613', '$16,387', '34.45%']],
    },
    notes: [
      'The flat 22% is a withholding rule, not a tax rate. It exists so employers do not have to guess your bracket once a year, and it is deliberately wrong in both directions.',
      'Payroll tax of 7.65% applies to bonuses because they are wages. Above the Social Security wage base only the 1.45% Medicare portion applies, so a very large bonus is withheld at a slightly lower effective rate.',
      'Retirement contributions are commonly taken from bonuses too. A 5% contribution reduces the cash you receive now and reduces the tax withheld, so the take-home figure falls by less than the contribution itself.',
    ],
    faqs: [
      ['Why is my bonus taxed so much?', 'It is usually withheld at a flat 22% rather than taxed at 22%. Add 7.65% of payroll tax and state tax, and the withheld amount reaches the mid-thirties as a percentage — which is higher than many people expect on a mid-range salary.'],
      ['Do I get the extra withholding back?', 'If the flat rate withheld more than your actual bracket requires, yes, when you file. If you are in a higher bracket, you may owe more. Either way, the withholding is only a deposit.'],
      ['Is it better to take a bonus as salary or as a bonus?', 'For an employee the tax treatment is the same; only the withholding method differs. For a business owner deciding between a bonus and a dividend, the answer depends on the corporate structure and cannot be settled by a withholding rate.'],
    ],
    links: ['calculators/after-tax-income', 'calculators/paycheck-breakdown', 'calculators/paycheck-calculator-2026', 'calculators/wage-growth-calculator-2026'],
    related: ['calculators/401k-calculator', 'calculators/savings-goal-calculator-2026', 'articles/pay-and-rates/gross-pay-vs-take-home-pay', 'calculators/net-worth-calculator-2026'],
  },
  {
    route: 'calculators/emergency-fund-calculator',
    h1: 'Emergency Fund Calculator: How Much to Hold',
    title: 'Emergency Fund Calculator: How Much You Need',
    desc: 'Work out the emergency fund that matches your essential monthly costs and see how long it would take to build at your current rate.',
    intent: 'tool',
    intro: 'Enter your essential monthly costs and the cover you want to see the target, the gap and how many months of saving it takes.',
    formula: { name: 'Emergency fund target', expr: 'target = essential monthly costs × months of cover', plain: 'Only essentials count: housing, food, utilities, insurance, transport and minimum debt payments. Discretionary spending is the first thing to stop in an emergency, so it is not in the target.' },
    assumptions: '$2,800 of essential monthly costs, six months of cover, $3,000 already saved at $400 a month.',
    caveat: 'The right number depends on how long replacing your income would take, not on a rule of thumb. Two incomes with secure jobs need less; a single freelancer with variable clients needs considerably more.',
    table: {
      head: ['Months of cover', 'Target', 'Gap from $3,000', 'Months to fill at $400'],
      rows: [['1', '$2,800', '$0', '0'], ['3', '$8,400', '$5,400', '14'], ['6', '$16,800', '$13,800', '35'], ['9', '$25,200', '$22,200', '56'], ['12', '$33,600', '$30,600', '77']],
    },
    notes: [
      'The fund exists to prevent a bad month becoming a bad year. Without it, a car repair goes on a 24% credit card and the interest turns a $900 problem into a $1,400 one.',
      'Where the money sits matters. It should be reachable within a day or two and not invested, because the moment you need it is often the moment markets have fallen.',
      'Building three months first and extending later is usually better than aiming at twelve and never starting. Each month of cover is a real reduction in the chance that a single event changes your finances permanently.',
    ],
    faqs: [
      ['How many months of expenses should an emergency fund cover?', 'Three to six months of essentials is the usual range; the right answer is how long it would take you to replace your income. Two secure salaries need less, a single variable income needs more.'],
      ['Should I build an emergency fund or pay off debt first?', 'Build one month of expenses, then attack the debt while paying the minimums, then return to the fund. A small buffer stops the next emergency going back onto the card you just cleared.'],
      ['Where should I keep an emergency fund?', 'A separate high-yield savings account. Separate so it is not absorbed into general spending; savings rather than investments so the balance is there when you need it.'],
    ],
    links: ['calculators/savings-goal-calculator-2026', 'calculators/50-30-20-budget-calculator', 'calculators/rent-affordability-calculator', 'calculators/debt-snowball-vs-avalanche-calculator'],
    related: ['guides/emergency-fund-hours', 'articles/saving-habits/how-big-should-my-emergency-fund-be', 'calculators/apy-calculator', 'calculators/after-tax-income'],
  },
  {
    route: 'calculators/401k-calculator',
    h1: '401(k) Calculator: Balance at Retirement',
    title: '401(k) Calculator: Balance at Retirement',
    desc: 'Project a 401(k) balance from your contribution, your employer match and a growth rate, and see which part of the balance is your money and which is growth.',
    intent: 'tool',
    intro: 'Enter your salary, contribution rate and employer match to see the projected balance and how much of it your employer contributes.',
    formula: { name: 'Retirement projection', expr: 'FV = balance × (1 + r)ⁿ + contribution × ((1 + r)ⁿ − 1) ÷ r', plain: 'The current balance compounds for the whole period; each year’s contribution compounds for the years remaining. The employer match is added to the contribution before either is calculated.' },
    assumptions: 'A $78,000 salary, an 8% contribution, a 50% match up to 6% of salary, a $45,000 starting balance and 27 years at 7%.',
    caveat: 'A constant annual return does not exist. Sequence matters as much as average: the same average with bad early years produces a materially smaller balance and a much smaller safe withdrawal.',
    table: {
      head: ['Years left', 'Balance', 'Contributed', 'Growth share'],
      rows: [['10', '$228,533', '$129,360', '43.4%'], ['20', '$528,780', '$233,720', '55.8%'], ['30', '$1,120,928', '$418,080', '62.7%'], ['40', '$2,305,565', '$681,440', '70.4%'],
      ],
    },
    notes: [
      'The employer match is the highest guaranteed return available to most people. Contributing enough to earn it, and nothing more, already captures most of the benefit; the tax advantage beyond that is real but smaller.',
      'The growth share column is the argument for starting early. At forty years, more than two-thirds of the balance is return rather than contributions, which no contribution rate can replicate over ten.',
      'Fees come out of the growth, not the contribution. One percentage point of extra cost over forty years removes roughly a quarter of the final balance, which is why the fund menu matters as much as the percentage you contribute.',
    ],
    faqs: [
      ['How much should I contribute to my 401(k)?', 'At minimum enough to earn the full employer match, because it is an instant return on the contribution. Beyond that, 15% of salary including the match is the common target for a retirement at the usual age.'],
      ['What does the employer match actually add?', 'A 50% match on the first 6% of salary is an extra half of the first 6% you contribute, immediately. On a $78,000 salary, contributing 6% is $4,680 and the match adds $2,340 a year.'],
      ['Is the projected balance realistic?', 'It is arithmetic, not a forecast. A constant 7% return every year has never happened; the number is useful for comparing contribution rates, not for predicting what you will have.'],
    ],
    links: ['calculators/compound-interest-calculator', 'calculators/roi-calculator', 'calculators/after-tax-income', 'calculators/apy-calculator'],
    related: ['calculators/net-worth-calculator-2026', 'calculators/inflation-calculator-2026', 'calculators/savings-goal-calculator-2026', 'calculators/wage-growth-calculator-2026'],
  },
  {
    route: 'calculators/moving-cost-calculator',
    h1: 'Moving Cost Calculator: The Full Bill',
    title: 'Moving Cost Calculator: The Full Bill',
    desc: 'Total up movers, deposit, fees, setup costs and your own time to see what a move really costs — the figure deposits and van hire leave out.',
    intent: 'tool',
    intro: 'Enter the distance, the quotes you have and the deposits you will pay to see the all-in cost of the move, including your own hours.',
    formula: { name: 'Cost of a move', expr: 'total = movers + deposit + fees + setup + (hours × hourly pay)', plain: 'Direct costs are the easy part. Valuing the hours you spend packing, cleaning and organising at your take-home rate is what turns a partial estimate into a real one.' },
    assumptions: 'An 850-mile move with $2,600 of movers, a $1,800 deposit, $400 of fees, $700 of setup and 30 hours of your own time at $27 an hour.',
    caveat: 'Quotes for long-distance moves are frequently revised on delivery day, and deposits are often non-refundable. Anything not in writing is not a quote, and the estimate is not the invoice.',
    table: {
      head: ['Distance', 'Movers', 'All-in cost', 'Cost per mile'],
      rows: [['50 mi', '$2,600', '$6,220', '$124.40'], ['250 mi', '$2,600', '$6,460', '$25.84'], ['850 mi', '$2,600', '$7,180', '$8.45'], ['2,000 mi', '$2,600', '$8,560', '$4.28']],
    },
    notes: [
      'Deposits, first month’s rent and setup costs are what make a move unaffordable, not the van. They are due before you have moved in and cannot be spread over the tenancy.',
      'Your own time is a genuine cost, and it is the one most often left out. Packing, cleaning, redirecting post, changing utilities and registering with a new doctor can easily reach thirty hours on a long-distance move.',
      'A move that shortens the commute permanently is worth far more than one that does not. Thirty minutes saved twice a day is more than two hundred hours a year, which is usually a larger figure than everything in this table combined.',
    ],
    faqs: [
      ['How much should I budget for a move?', 'Local moves usually cost a few hundred dollars plus deposits; long-distance moves are quoted by weight and distance and run into thousands. Deposits and setup costs are typically as large again as the moving company.'],
      ['Are moving costs tax deductible?', 'For a job-related move meeting the distance and time tests, some jurisdictions allow a deduction; in the United States, the deduction was removed for most employees by the 2017 tax changes. Check the current rules for your situation.'],
      ['Is it cheaper to hire movers or a van?', 'A van is cheaper if your time is worth little and you have help. Movers are cheaper once you count the hours, the damage deposit and the risk of an injury carrying a sofa down a staircase.'],
    ],
    links: ['calculators/rent-affordability-calculator', 'calculators/commute-cost', 'calculators/cost-of-living-calculator-2026', 'calculators/time-to-save'],
    related: ['calculators/emergency-fund-calculator', 'articles/spending-decisions/seven-questions-before-a-big-purchase', 'calculators/down-payment-calculator', 'calculators/net-worth-calculator-2026'],
  },
  {
    route: 'calculators/pet-cost-calculator',
    h1: 'Pet Cost Calculator: Lifetime Cost of a Pet',
    title: 'Pet Cost Calculator: Lifetime Cost of a Pet',
    desc: 'Estimate what a dog or cat costs over their whole life, including food, insurance, vet care and one emergency bill. Free and private.',
    intent: 'tool',
    intro: 'Enter monthly costs, annual extras, one-off setup and a realistic emergency figure to see the lifetime total and the cost per month.',
    formula: { name: 'Lifetime pet cost', expr: 'total = setup + (monthly × 12 + annual) × years + emergency', plain: 'Monthly and annual costs both repeat for every year of the pet’s life. The one-off setup and the emergency bill are added once, because they happen once.' },
    assumptions: 'A dog kept for 13 years at $145 a month, $420 a year of extras, $600 of setup and one $2,500 emergency vet bill.',
    caveat: 'Breed, age and insurance coverage move these numbers more than anything else. A pet adopted at eight years old with a pre-existing condition has a very different cost profile from a healthy puppy.',
    table: {
      head: ['Years lived', 'Lifetime cost', 'Cost a year', 'Cost a month'],
      rows: [['5', '$13,320', '$2,664', '$222'], ['10', '$23,740', '$2,374', '$198'], ['13', '$31,180', '$2,399', '$200'], ['15', '$35,620', '$2,375', '$198'], ['20', '$46,780', '$2,339', '$195']],
    },
    notes: [
      'The monthly figure is the one to compare with your budget, because that is the shape the cost actually takes. Most of a pet’s cost arrives as small, regular payments rather than one large decision.',
      'Insurance changes the shape rather than the total, in most cases. Premiums over a healthy pet’s life often exceed the bills they cover, and the value comes from the cap on a single catastrophic event.',
      'The emergency column is what makes the arithmetic worth doing before adopting. A single uninsured surgery can exceed every routine expense of the first five years combined.',
    ],
    faqs: [
      ['How much does a dog cost over its lifetime?', 'Twenty to thirty-five thousand dollars for a medium-sized dog over thirteen years is a reasonable range, depending on food quality, insurance and veterinary costs in your area. Large breeds and city vets push it higher.'],
      ['Should I get pet insurance?', 'It depends on whether you would hesitate over a $3,000 bill. Insurance converts a large, unpredictable cost into a smaller, predictable one; it does not usually reduce the total spent.'],
      ['Are cats cheaper than dogs?', 'Usually, by roughly a third. The gap comes from food, boarding and the frequency of routine veterinary care rather than from any difference in emergencies.'],
    ],
    links: ['calculators/child-cost-calculator-2026', 'calculators/emergency-fund-calculator', 'calculators/50-30-20-budget-calculator', 'calculators/cost-per-use'],
    related: ['calculators/net-worth-calculator-2026', 'articles/saving-habits/sinking-funds-explained', 'calculators/savings-goal-calculator-2026', 'calculators/daily-savings'],
  },
  {
    route: 'calculators/electricity-cost-calculator',
    h1: 'Electricity Cost Calculator: What a Device Costs to Run',
    title: 'Electricity Cost Calculator: Appliance Running Cost',
    desc: 'Work out what any appliance costs to run from its wattage, the hours you use it and your price per kWh — monthly, daily and per hour.',
    intent: 'tool',
    intro: 'Enter the power rating, the hours it runs each day and your electricity price to see what the device adds to your bill.',
    formula: { name: 'Running cost', expr: 'kWh = watts ÷ 1000 × hours × days;  cost = kWh × price', plain: 'Convert watts to kilowatts, multiply by the hours used, then by the price per kilowatt hour. The kilowatt hour is what the utility actually bills.' },
    assumptions: 'A 1,500 W heater used four hours a day for 30 days at 17 cents per kWh.',
    caveat: 'Appliances with a compressor, a thermostat or a standby mode do not draw a constant wattage. For those, a plug-in energy monitor gives a better figure than the rating plate.',
    table: {
      head: ['Power', 'kWh a month', 'Cost a month', 'Cost a year'],
      rows: [['10 W', '1.2', '$0.20', '$2.45'], ['100 W', '12.0', '$2.04', '$24.48'], ['1,500 W', '180.0', '$30.60', '$367.20'], ['3,000 W', '360.0', '$61.20', '$734.40'], ['7,000 W', '840.0', '$142.80', '$1,713.60']],
    },
    notes: [
      'Heating and cooling dominate household electricity because they run for hours, not because they draw the most watts. A 1,500 W heater for four hours uses more than a 7,000 W appliance switched on for forty minutes.',
      'The price per kilowatt hour on your bill is not one number. Supply, delivery and standing charges are usually quoted separately, and the effective rate is the total divided by the kilowatt hours used.',
      'Standby loads are small individually and significant together: a house of devices drawing 10 W continuously costs roughly $15 a year at average rates, and that is the floor of the bill rather than the ceiling.',
    ],
    faqs: [
      ['How do I calculate the cost of running an appliance?', 'Multiply its wattage by the hours used, divide by 1,000 to get kilowatt hours, then multiply by your price per kWh. A 1,500 W heater for four hours uses 6 kWh, which is about $1.02 at 17 cents.'],
      ['How much does it cost to run a space heater all day?', 'A 1,500 W heater running continuously for ten hours uses 15 kWh. At 17 cents that is $2.55 a day, or around $76 a month if used every day.'],
      ['Is a higher wattage always more expensive?', 'No. What matters is the energy used, which is wattage multiplied by time. A 2,000 W kettle for three minutes can cost less per use than a 200 W device left on all evening.'],
    ],
    links: ['calculators/gas-cost-calculator', 'calculators/commute-cost', 'calculators/50-30-20-budget-calculator', 'calculators/inflation-calculator-2026'],
    related: ['calculators/car-ownership-cost', 'articles/subscriptions/how-to-audit-your-subscriptions', 'calculators/subscription-audit', 'calculators/cost-of-living-calculator-2026'],
  },
  {
    route: 'calculators/down-payment-calculator',
    h1: 'Down Payment Calculator: Cash Needed to Buy',
    title: 'Down Payment Calculator: Cash You Need',
    desc: 'Work out the cash needed to buy a home: down payment, closing costs and a reserve — and what 20% down would take.',
    intent: 'tool',
    intro: 'Enter a home price and a percentage to see the deposit, the closing costs and the cash you need on the day, including a reserve.',
    formula: { name: 'Cash to close', expr: 'cash = price × down% + price × closing% + reserve', plain: 'The down payment is the visible part. Closing costs are typically 2% to 5% of the price on top, and a reserve keeps the first repair off a credit card.' },
    assumptions: 'A $420,000 home with 10% down, 2.5% closing costs and a $9,000 reserve.',
    caveat: 'Anything below 20% down usually triggers mortgage insurance, which is a monthly cost that no deposit calculation shows. It falls away once you have enough equity, but rarely automatically.',
    table: {
      head: ['Down payment', 'Cash needed', 'Monthly PMI if under 20%', 'Loan amount'],
      rows: [['3.0%', '$31,590', '$173.25', '$407,400'], ['5.0%', '$39,990', '$166.25', '$399,000'], ['10.0%', '$61,500', '$157.50', '$378,000'], ['15.0%', '$83,010', '$148.75', '$357,000'], ['20.0%', '$104,500', '$0', '$336,000']],
    },
    notes: [
      'Closing costs are the line that surprises first-time buyers. Origination fees, title insurance, appraisal, survey and prepaid taxes typically add 2% to 5% of the purchase price, payable on the same day as the deposit.',
      'Keeping a reserve is not optional in practice. A house with no cash left after closing turns a $600 repair into credit card debt, which is the opposite of what a deposit is supposed to achieve.',
      'Gift money for a deposit is usually allowed but must be documented, and some loan programmes limit how much of the down payment can come from a gift. Ask before you accept the transfer.',
    ],
    faqs: [
      ['How much is a down payment on a house?', 'Twenty per cent is the conventional figure because it avoids mortgage insurance. Many first-time buyer programmes accept 3% to 5%, and some allow less, at the cost of a monthly insurance premium.'],
      ['Do closing costs count towards the down payment?', 'No, they are separate and additional. Budget 2% to 5% of the purchase price on top of the deposit, and expect to pay it on the day of closing rather than spreading it.'],
      ['How do I get rid of mortgage insurance?', 'Once you have at least 20% equity, most loans allow you to request removal, and some remove it automatically at 22% based on the original schedule. It requires a request and often an appraisal, so it does not vanish on its own.'],
    ],
    links: ['calculators/mortgage-calculator-2026', 'calculators/rent-vs-buy-calculator-2026', 'calculators/rent-affordability-calculator', 'calculators/savings-goal-calculator-2026'],
    related: ['guides/how-much-house-can-i-afford-2026', 'calculators/time-to-save', 'articles/spending-decisions/should-you-rent-or-buy', 'calculators/apy-calculator'],
  },
  {
    route: 'calculators/apy-calculator',
    h1: 'APY Calculator: Nominal Rate to Effective Rate',
    title: 'APY Calculator: Nominal Rate to APY',
    desc: 'Convert a nominal interest rate into APY and see what compounding frequency is really worth on your balance. Free, private, no sign-up.',
    intent: 'tool',
    intro: 'Enter a nominal rate and a compounding frequency to see the effective annual rate and what it earns on a balance.',
    formula: { name: 'Effective annual rate', expr: 'APY = (1 + APR ÷ n)ⁿ − 1', plain: 'A nominal rate divided by the number of compounding periods, compounded that many times, produces a slightly higher effective rate. The more often it compounds, the larger the gap.' },
    assumptions: 'A 4.5% nominal rate on a $10,000 balance held for three years.',
    caveat: 'APY assumes the rate stays unchanged and the interest stays invested. Both assumptions fail on a variable-rate account, and the guaranteed rate on most savings accounts lasts only as long as the bank decides.',
    table: {
      head: ['Compounding', 'APY', 'After one year', 'After three years'],
      rows: [['1× a year', '4.50%', '$10,450.00', '$11,411.66'], ['2× a year', '4.55%', '$10,455.06', '$11,424.13'], ['4× a year', '4.58%', '$10,457.65', '$11,432.13'], ['12× a year', '4.59%', '$10,459.40', '$11,437.31'], ['365× a year', '4.60%', '$10,460.25', '$11,440.90']],
    },
    notes: [
      'The gap between annual and daily compounding at 4.5% is about $10 on a $10,000 balance in the first year. It is small, and it is the only difference between two accounts quoting the same nominal rate.',
      'Quoting the nominal rate flatters a loan and understates a deposit. Lenders are required to disclose APY on deposits precisely so that the two can be compared, so compare APY against APY and APR against APR.',
      'With continuous compounding, APY equals e raised to the nominal rate minus one. Even infinite compounding only adds about a tenth of a percentage point to a 4.5% rate, which is why daily is effectively the practical limit.',
    ],
    faqs: [
      ['What is the difference between APR and APY?', 'APR is the nominal annual rate without compounding; APY includes the effect of compounding within the year. For a deposit, APY is the number to compare. For a loan, APR includes fees and is the number to compare.'],
      ['Does compounding frequency matter much?', 'Less than people assume. The difference between monthly and daily compounding at 4.5% is about a dollar a year on $10,000. The rate itself matters far more.'],
      ['How do I convert APY back to a nominal rate?', 'Divide the APY as a decimal plus one by the compounding frequency, take that root, subtract one and multiply by the frequency. Most people never need to: compare APY to APY and stop there.'],
    ],
    links: ['calculators/compound-interest-calculator', 'calculators/savings-goal-calculator-2026', 'calculators/roi-calculator', 'calculators/inflation-calculator-2026'],
    related: ['calculators/401k-calculator', 'calculators/emergency-fund-calculator', 'calculators/investment-return-calculator-2026', 'calculators/net-worth-calculator-2026'],
  },
];

export const SUITE_ROUTES = SUITE_CONTENT.map(c => c.route);
export { H as SUITE_REPO_URL };
