import fs from 'node:fs';
import vm from 'node:vm';
export const routes = ['calculators/cost-of-time','calculators/subscription-cost','calculators/daily-savings','guides/hourly-pay','guides/small-purchases','guides/24-hour-rule'];
export function generateSEO() {
const raw = process.env.SITE_URL;
let origin='';
if(raw){const u=new URL(raw);if(!['https:','http:'].includes(u.protocol)||u.pathname!=='/'||u.search||u.hash)throw Error('SITE_URL must be a site origin, e.g. https://your-domain.com');origin=u.origin;}
if(process.env.REQUIRE_SITE_URL && !origin)throw Error('Set SITE_URL to your production origin before a production build.');
const base=fs.readFileSync('index.html','utf8');
const articles=vm.runInNewContext('('+fs.readFileSync('app.js','utf8').match(/const articles=(\{.*?\});\ndocument/s)[1]+')');
const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
const data=[
{route:routes[0],name:'Cost of Time Calculator',title:'Cost of Time Calculator: Convert Money to Work Hours | Worth',description:'Find how many work hours a purchase costs using your after-tax hourly, monthly, or annual pay. Free calculator with the formula and worked examples.',mode:'purchase',intro:'How many hours of work does that purchase cost? Enter the price and your take-home pay to see the trade-off.',body:`<h2>How to calculate the work hours behind a purchase</h2><p><strong>Work hours = purchase price ÷ take-home hourly pay.</strong> A $150 purchase at $25 per hour takes 6 hours of work. This number is a different way to look at spending, not a judgment about what you should buy.</p><h3>Converting a monthly or annual salary</h3><p>For a 40-hour week over 52 weeks, annual work time is 2,080 hours. Divide annual take-home pay by 2,080, or monthly take-home pay by 173.33. Someone taking home $52,000 per year has an estimated $25 hourly rate. If you work different hours, enter your actual hourly pay instead.</p><h3>Worked examples at $25 take-home per hour</h3><table><thead><tr><th>Purchase</th><th>Price</th><th>Work hours</th></tr></thead><tbody><tr><td>Dinner out</td><td>$50</td><td>2 hours</td></tr><tr><td>Sneakers</td><td>$150</td><td>6 hours</td></tr><tr><td>Laptop</td><td>$1,000</td><td>40 hours</td></tr></tbody></table><h3>What this calculation leaves out</h3><p>It does not account for rent, bills, savings obligations, or the emotional value of a purchase. Your full take-home wage is not all disposable income. Use the result as perspective, not as an affordability assessment.</p>`},
{route:routes[1],name:'Subscription Cost Calculator',title:'Subscription Cost Calculator: Monthly to Yearly Cost | Worth',description:'Convert monthly subscription fees into annual costs and hours of work. See the real cost of streaming, apps, and memberships with a free calculator.',mode:'subscription',intro:'A small monthly charge can become a big yearly commitment. See your annual subscription cost in dollars and work hours.',body:`<h2>Calculate the annual cost of a subscription</h2><p><strong>Annual cost = monthly price × 12.</strong> A $15 monthly subscription costs $180 per year. At $25 per hour in take-home pay, that is 7.2 hours of work each year.</p><h3>Common monthly costs, annualized</h3><table><thead><tr><th>Monthly fee</th><th>Yearly cost</th><th>Hours at $25/hour</th></tr></thead><tbody><tr><td>$10</td><td>$120</td><td>4.8</td></tr><tr><td>$15</td><td>$180</td><td>7.2</td></tr><tr><td>$50</td><td>$600</td><td>24</td></tr></tbody></table><h3>Check several subscriptions together</h3><p>Add the monthly costs of your services and enter that total. Three services costing $10, $15, and $20 a month total $45 monthly, or $540 annually. At $25 take-home per hour, they represent 21.6 work hours.</p><h3>Is an annual plan actually cheaper?</h3><p>Compare the quoted annual price with the monthly fee multiplied by 12. A $150 annual plan versus $15 per month saves $30 only if you would otherwise keep the service for all 12 months. Check cancellation terms and taxes before switching.</p><p>This calculator assumes the monthly fee stays constant and is paid for a full year. It does not include discounts, trials, or price increases unless you include them in your input.</p>`},
{route:routes[2],name:'Daily Savings Calculator',title:'Daily Savings Calculator: Small Habits, Yearly Savings | Worth',description:'See how saving $1, $5, or $10 a day adds up over a year. Calculate simple daily savings without assumed investment returns or interest.',mode:'saving',intro:'What could one small daily change add up to? Turn a daily amount into a yearly saving—and see the time it represents.',body:`<h2>Turn a daily habit into a yearly saving</h2><p><strong>Yearly savings = daily amount × 365.</strong> Setting aside $5 each day adds up to $1,825 over a 365-day year. This is money set aside, not an investment forecast.</p><h3>How much could you save in a year?</h3><table><thead><tr><th>Daily amount</th><th>Over 30 days</th><th>Over 365 days</th></tr></thead><tbody><tr><td>$1</td><td>$30</td><td>$365</td></tr><tr><td>$5</td><td>$150</td><td>$1,825</td></tr><tr><td>$10</td><td>$300</td><td>$3,650</td></tr></tbody></table><h3>What about coffee only on weekdays?</h3><p>The calculator assumes a daily habit. If you skip a $5 purchase five times a week for 52 weeks, the result is $1,300—not $1,825. For twice a week, it is $520. Use the schedule that matches your life.</p><h3>Make the change sustainable</h3><p>Pick a purchase you will not miss, and move the amount into a separate savings pot. Cutting a purchase does not increase savings if the money is simply spent elsewhere. Keep the things that give you real value.</p><p>These estimates exclude interest, investment returns, inflation, leap days, and changes in the daily amount. Work-hour equivalents use your take-home pay, not your disposable income after bills.</p>`},
...['time','habits','rule'].map((key,i)=>({route:routes[3+i],name:articles[key].title,title:articles[key].title+' | Worth',description:articles[key].body[0][1].slice(0,155),body:articles[key].body.map(([h,p])=>`<h2>${escape(h)}</h2><p>${escape(p)}</p>`).join('')}))
];
const links=`<section class="seo-related"><div class="section-label">MORE WAYS TO FIND PERSPECTIVE</div><h2>Free calculators & practical guides</h2><div>${data.map(p=>`<a href="/${p.route}/">${escape(p.name)} <span>↗</span></a>`).join('')}</div></section>`;
function metadata(html,p){const url=origin+(p.route?'/'+p.route+'/':'/');html=html.replace(/<title>.*?<\/title>/,`<title>${escape(p.title)}</title>`).replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${escape(p.description)}">`).replace(/<meta property="og:title" content="[^"]*">/,`<meta property="og:title" content="${escape(p.title)}">`).replace(/<meta property="og:description" content="[^"]*">/,`<meta property="og:description" content="${escape(p.description)}">`);
const schema={'@context':'https://schema.org','@graph':[{'@type':'WebSite',name:'Worth',...(origin?{url:origin+'/'}:{})},{'@type':p.mode?'WebApplication':'WebPage',name:p.name,description:p.description,...(origin?{url}:{}),...(p.mode?{applicationCategory:'FinanceApplication',operatingSystem:'Any',offers:{'@type':'Offer',price:'0',priceCurrency:'USD'}}:{})},...(p.route?[{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',...(origin?{item:origin+'/'}:{})},{'@type':'ListItem',position:2,name:p.name,...(origin?{item:url}:{})}]}]:[])]};
html=html.replace(/<script type="application\/ld\+json">.*?<\/script>/s,`<script type="application/ld+json">${JSON.stringify(schema).replaceAll('<','\\u003c')}</script>`);
return html.replace('</head>',`${origin?`<link rel="canonical" href="${escape(url)}"><meta property="og:url" content="${escape(url)}">`:'<meta name="robots" content="noindex, nofollow">'}<meta name="twitter:card" content="summary"></head>`);}
for(const p of data){const crumb=`<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><span>${escape(p.name)}</span></nav>`;const hero=`${crumb}<section class="seo-hero"><div class="eyebrow">${p.mode?'FREE MONEY CALCULATOR':'THE MONEY EDIT'}</div><h1>${escape(p.name)}</h1>${p.intro?`<p>${p.intro}</p>`:''}</section>`;let calculator=p.mode?base.match(/<section id="calculator"[\s\S]*?<\/section>/)[0]:'';
if(p.mode && p.mode!=='purchase'){
 const sub=p.mode==='subscription';
 calculator=calculator.replace('Is it worth your time?',sub?'Small monthly. Big yearly.':'Little habits. More possibility.').replace('That price tag has a story. Let’s put it in hours.',sub?'See what a recurring charge really adds up to.':'What could one small daily change free up?').replace('How much does it cost?',sub?'Monthly subscription cost':'Daily amount to set aside').replace('value="150"',sub?'value="15"':'value="5"').replace('id="cost-suffix">USD','id="cost-suffix">'+(sub?'/ mo':'/ day')).replace('That purchase costs you',sub?'That subscription costs you each year':'That daily habit could free up').replace('id="hours">6',sub?'id="hours">7.2':'id="hours">$1,825').replace('id="unit">hours',sub?'id="unit">hours':'id="unit">/ year').replace('of your working life.',sub?'of your working life.':'equivalent to 73 hours of your working life.').replace('¾ of a workday',sub?'7.2 of 8 working hours':'9.1 workdays').replace('Not good. Not bad. Just perspective.<br>Only you can decide if it’s worth it.',sub?'$15 a month is $180 a year. If it adds value to your life, it might be time well spent.':'$5 a day, for 365 days. No investment returns assumed—just a small change adding up.').replace('aria-selected="true" data-mode="purchase"','aria-selected="false" data-mode="purchase"').replace('aria-selected="false" data-mode="'+p.mode+'"','aria-selected="true" data-mode="'+p.mode+'"');
}
const faq=p.mode?base.match(/<section class="faq"[\s\S]*?<\/section>/)[0]:'';let html=base.replace(/<main>[\s\S]*?<\/main>/,`<main>${hero}${calculator}<article class="seo-article">${p.body}</article>${links}${faq}</main>`).replace('<body>',`<body data-mode="${p.mode||''}">`).replace(/href="#(calculator|learn|how)"/g,'href="/#$1"');if(!p.mode)html=html.replace(/<button class="saved-button"[\s\S]*?<\/button>/,'<a class="saved-button" href="/calculators/cost-of-time/">Try the calculator ↗</a>').replace('<script type="module" src="/app.js"></script>','');html=metadata(html,p);fs.mkdirSync(p.route,{recursive:true});fs.writeFileSync(p.route+'/index.html',html);}
// This template is the source of the homepage; the generated file is served by Vite.
let home=metadata(base.replace('<!-- SEO_LINKS -->',links),{name:'Worth Money Calculators',title:'Free Money Calculators: Work Hours, Subscriptions & Savings | Worth',description:'Convert prices to work hours, check annual subscription costs, and see daily savings add up. Free money calculators and practical guides for intentional spending.'});
fs.mkdirSync('.generated',{recursive:true});fs.writeFileSync('.generated/home.html',home);
fs.mkdirSync('public',{recursive:true});fs.writeFileSync('public/robots.txt',origin?`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`:'User-agent: *\nDisallow: /\n');
if(origin)fs.writeFileSync('public/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['',...routes].map(r=>`<url><loc>${escape(origin+(r?'/'+r+'/':'/'))}</loc></url>`).join('')}</urlset>`);else if(fs.existsSync('public/sitemap.xml'))fs.unlinkSync('public/sitemap.xml');
return home;
}
if(process.argv[1]?.endsWith('generate-seo.mjs'))generateSEO();
