// Per-page content for the 40 "extra" routes. Every page gets its own title,
// description, intro, sections, a data table, and FAQs. No two pages share a
// body, and every calculator page is framed around the one calculation the
// embedded widget really performs: price ÷ take-home hourly pay = hours of work.
//
// Keep titles under ~60 chars and descriptions under ~155 chars.

const T = (headers, rows) => ({ headers, rows });

export const HOURLY_WAGE_CLUSTER = {
  en: 'calculators/salary-to-hourly',
  es: 'guides/calculadora-salario-hora-2026-latam',
  de: 'guides/stundenlohn-rechner-deutschland-2026',
  fr: 'guides/calculateur-salaire-horaire-france-2026',
  ru: 'guides/калькулятор-зарплаты-час-россия-2026',
  zh: 'guides/时薪计算器-中国-2026',
  ja: 'guides/時給計算機-日本-2026',
  ko: 'guides/연봉-시급-계산기-한국-2026',
  ar: 'guides/حاسبة-الراتب-بالساعة-السعودية-2026',
  pt: 'guides/calculadora-horas-trabalho-brasil-2026',
};

export const pages = {
  'calculators/mortgage-calculator-2026': {
    name: 'Mortgage Payment in Work Hours Calculator',
    title: 'Mortgage Payment in Hours of Work Calculator (2026) | Worth',
    description: 'Convert a monthly mortgage payment into hours of work at your take-home pay. Formula, 2026 payment table at 6–7% rates, and what the number leaves out.',
    intro: 'Enter your monthly mortgage payment and take-home hourly pay to see how many working hours each month go to the house.',
    keywords: ['mortgage calculator', 'mortgage payment in hours', 'housing cost work hours'],
    sections: [
      ['How many hours of work a mortgage payment costs', '<p><strong>Hours per month = monthly payment ÷ take-home hourly pay.</strong> A $2,200 payment at $30 per hour after tax is 73 hours, or about 42% of a 173-hour working month. Lenders talk about debt-to-income; this is the same idea expressed in time.</p>'],
      ['Estimating the payment first', '<p>For a fixed-rate loan the monthly principal-and-interest payment is <em>P × r ÷ (1 − (1 + r)<sup>−n</sup>)</em>, where <em>r</em> is the monthly rate and <em>n</em> the number of payments. At 6.5% over 30 years, every $100,000 borrowed costs about $632 a month. Add property tax and insurance before dividing by your hourly pay.</p>'],
      ['What the hours figure leaves out', '<p>It ignores equity you build, tax treatment, and rent you would otherwise pay. Use it to compare two homes or a house against renting at the same hourly rate, not as an affordability rule on its own.</p>'],
    ],
    table: T(['Loan amount (6.5%, 30 yr)', 'P&I per month', 'Hours at $30/hr'], [['$250,000', '$1,580', '53 h'], ['$350,000', '$2,212', '74 h'], ['$450,000', '$2,844', '95 h'], ['$600,000', '$3,792', '126 h']]),
    faqs: [
      ['How do I convert a mortgage payment to hours of work?', 'Divide the full monthly payment (principal, interest, tax, insurance) by your after-tax hourly pay. $2,200 ÷ $30 = 73 hours a month.'],
      ['What share of my working month should go to housing?', 'Common guidance keeps housing under 28–30% of gross income, which is roughly 50–60 hours of a 173-hour month at take-home rates. Your other debts and savings goals matter more than the rule.'],
      ['Does this include property tax and insurance?', 'Only if you add them to the payment you enter. Escrowed tax and insurance often add 20–30% to the principal-and-interest figure.'],
    ],
  },
  'calculators/compound-interest-calculator': {
    name: 'Compound Interest in Hours Calculator',
    name_short: 'Compound interest',
    title: 'Compound Interest Calculator: Hours of Work Saved | Worth',
    description: 'See what compound growth is worth in hours of work. Formula, a 7% growth table from $1,000 to $50,000, and how long money takes to double.',
    intro: 'Enter a future balance and your hourly pay to see how many hours of work the growth alone represents.',
    keywords: ['compound interest calculator', 'compound growth hours of work', 'rule of 72'],
    sections: [
      ['The compound interest formula', '<p><strong>A = P × (1 + r/n)<sup>n·t</sup>.</strong> $10,000 at 7% compounded yearly for 20 years grows to $38,697. The $28,697 of growth at $30 per hour is 957 hours of work you did not have to do.</p>'],
      ['Rule of 72', '<p>Divide 72 by the annual rate to estimate doubling time: 72 ÷ 7 ≈ 10.3 years. At 4% it is 18 years; at 10% about 7. This is why starting earlier beats contributing more later.</p>'],
      ['Turning growth into hours', '<p>Enter the interest earned, not the whole balance, into the calculator above. That isolates the part you did not work for. Real returns vary year to year; 7% is a long-run nominal average for diversified stocks, not a promise.</p>'],
    ],
    table: T(['Starting amount', 'After 20 yr at 7%', 'Growth', 'Hours at $30/hr'], [['$1,000', '$3,870', '$2,870', '96 h'], ['$5,000', '$19,348', '$14,348', '478 h'], ['$10,000', '$38,697', '$28,697', '957 h'], ['$50,000', '$193,484', '$143,484', '4,783 h']]),
    faqs: [
      ['How is compound interest calculated?', 'A = P(1 + r/n)^(nt). P is principal, r the annual rate, n compounding periods per year, t years.'],
      ['How long does money take to double at 7%?', 'About 10.3 years using the rule of 72 (72 ÷ 7).'],
      ['Why express growth in hours of work?', 'Because it makes the alternative concrete: 957 hours of growth is about 24 full working weeks you did not have to trade for the money.'],
    ],
  },
  'calculators/inflation-calculator-2026': {
    name: 'Inflation Cost in Work Hours Calculator',
    title: 'Inflation Calculator 2026: Price Rises in Hours of Work | Worth',
    description: 'Measure inflation in hours of work instead of percent. Formula, a table of common prices 2020 vs 2026, and how to check if your pay kept up.',
    intro: 'Enter a price today and your hourly pay to see how many hours it costs now versus a few years ago.',
    keywords: ['inflation calculator', 'inflation in hours of work', 'real wage calculator'],
    sections: [
      ['Inflation measured in your time', '<p><strong>Hours = price ÷ take-home hourly pay.</strong> If groceries that cost $100 in 2020 cost $126 in 2026 and your pay rose from $25 to $29, the basket went from 4.0 hours to 4.3 hours. Inflation only hurts when prices rise faster than your wage.</p>'],
      ['Cumulative inflation formula', '<p>Price<sub>now</sub> = Price<sub>then</sub> × (1 + i)<sup>years</sup>. Average 4% a year over six years compounds to about 26.5%, not 24%. The US CPI rose roughly 25% between early 2020 and 2025.</p>'],
      ['Did your pay keep up?', '<p>Divide your current hourly pay by your 2020 hourly pay. If the ratio is below the price ratio, your real hourly wage fell. Run both numbers through the calculator to see the gap in hours.</p>'],
    ],
    table: T(['Item', '2020 price', '2026 price (est.)', 'Hours at $25 → $29/hr'], [['Weekly groceries', '$100', '$126', '4.0 → 4.3 h'], ['Tank of gas', '$35', '$46', '1.4 → 1.6 h'], ['Used car', '$20,000', '$27,000', '800 → 931 h'], ['Streaming bundle', '$30', '$45', '1.2 → 1.6 h']]),
    faqs: [
      ['How do I calculate inflation between two years?', 'Divide the later price by the earlier price and subtract 1. $126 ÷ $100 − 1 = 26% cumulative inflation.'],
      ['What is a real wage?', 'Your pay adjusted for inflation. If pay rose 16% and prices 26%, your real wage fell about 8%.'],
      ['Why measure inflation in hours?', 'Percentages hide the trade-off. Hours show whether a fixed basket now consumes more or less of your working life.'],
    ],
  },
  'calculators/paycheck-calculator-2026': {
    name: 'Paycheck to Hourly Take-Home Calculator',
    title: 'Paycheck Calculator 2026: Net Pay Per Hour Worked | Worth',
    description: 'Turn a paycheck into true take-home pay per hour. Federal, FICA and state deductions explained, 2026 example table, and how to use net hourly pay.',
    intro: 'Enter your net paycheck and the hours behind it to find what an hour of work actually puts in your account.',
    keywords: ['paycheck calculator', 'take home pay per hour', 'net hourly wage'],
    sections: [
      ['Net pay per hour', '<p><strong>Net hourly pay = take-home paycheck ÷ hours worked in the period.</strong> A biweekly net check of $2,150 for 80 hours is $26.88 per hour, even if your gross rate is $35. That net number is the one to use in every cost-of-time calculation.</p>'],
      ['What comes out of a US paycheck in 2026', '<p>Federal income tax (10–37% brackets), Social Security 6.2% up to the wage base, Medicare 1.45%, state income tax in most states, plus pre-tax 401(k) and health premiums. A typical single filer at $70,000 nets around 75–78% of gross.</p>'],
      ['Using the number', '<p>Once you know net hourly pay, every price divides cleanly into hours. A $300 purchase at $26.88 net is 11.2 hours, not the 8.6 hours a gross rate suggests.</p>'],
    ],
    table: T(['Gross salary', 'Gross hourly (2,080 h)', 'Approx. net (single, no state tax)', 'Net hourly'], [['$45,000', '$21.63', '$37,300', '$17.93'], ['$70,000', '$33.65', '$54,900', '$26.39'], ['$100,000', '$48.08', '$75,100', '$36.11'], ['$150,000', '$72.12', '$107,700', '$51.78']]),
    faqs: [
      ['How do I find my hourly pay from a paycheck?', 'Divide the net amount by the hours in the pay period. Biweekly full-time is usually 80 hours; semi-monthly about 86.67.'],
      ['Why is net hourly pay lower than my wage?', 'Taxes and deductions typically remove 20–30% before the money reaches you.'],
      ['Should I include benefits?', 'For cost-of-time decisions, no; use cash that actually lands in your account.'],
    ],
  },
  'calculators/crypto-profit-calculator-2026': {
    name: 'Crypto Profit in Hours of Work Calculator',
    title: 'Crypto Profit Calculator: Gains and Losses in Work Hours | Worth',
    description: 'Convert a crypto gain or loss into hours of work at your pay. Profit formula with fees, a break-even table, and how to think about volatility in time.',
    intro: 'Enter your realized profit or loss and your hourly pay to see what the trade was worth in working hours.',
    keywords: ['crypto profit calculator', 'bitcoin profit hours of work', 'crypto gains calculator'],
    sections: [
      ['Profit formula', '<p><strong>Profit = (sell price − buy price) × quantity − fees.</strong> Buying 0.1 BTC at $60,000 and selling at $68,000 with $40 in fees nets $760. At $30 per hour that is 25 hours of work, before capital gains tax.</p>'],
      ['Losses in hours', '<p>The same trade in reverse loses 25 hours plus fees. Run losses through the calculator too; people rarely translate drawdowns into time, which is why they feel smaller than they are.</p>'],
      ['Taxes and break-even', '<p>Short-term gains are taxed as ordinary income in the US. Break-even price = buy price × (1 + fee rate)<sup>2</sup> ÷ 1, so a 0.5% fee each way needs about a 1% move to reach zero.</p>'],
    ],
    table: T(['Position', 'Move', 'Profit before tax', 'Hours at $30/hr'], [['$1,000', '+10%', '$100', '3.3 h'], ['$5,000', '+10%', '$500', '16.7 h'], ['$5,000', '−20%', '−$1,000', '−33 h'], ['$20,000', '+25%', '$5,000', '167 h']]),
    faqs: [
      ['How do I calculate crypto profit?', 'Subtract total cost (buy price × quantity + fees) from total proceeds (sell price × quantity − fees).'],
      ['Are crypto gains taxed?', 'In most countries yes. In the US, assets held under a year are taxed as ordinary income; over a year at long-term rates.'],
      ['Why convert profit to hours?', 'It anchors a volatile number to something stable: 167 hours is a month of work, whether the coin doubled or you got lucky.'],
    ],
  },
  'calculators/youtube-earnings-calculator-2026': {
    name: 'YouTube Earnings Per Hour Calculator',
    title: 'YouTube Earnings Calculator 2026: RPM, Views, Pay Per Hour | Worth',
    description: 'Estimate YouTube AdSense income from views and RPM, then divide by the hours you spend making videos. 2026 RPM table by niche and an hourly-rate check.',
    intro: 'Enter estimated monthly channel revenue and the hours you put in to see your effective hourly rate.',
    keywords: ['youtube earnings calculator', 'youtube money calculator', 'youtube rpm 2026'],
    sections: [
      ['Revenue formula', '<p><strong>Earnings = (monetized views ÷ 1,000) × RPM.</strong> RPM (revenue per mille) is what you keep after YouTube&rsquo;s 45% cut. A channel with 500,000 views a month at a $4 RPM earns $2,000.</p>'],
      ['Turning it into an hourly rate', '<p>Divide revenue by production hours. If those 500,000 views took 4 videos at 15 hours each, $2,000 ÷ 60 hours = $33 per hour. Most small channels land below minimum wage on this measure for the first year or two.</p>'],
      ['Typical 2026 RPMs', '<p>Finance and software channels see $8–$20 RPM; gaming and vlogs often $1–$3; Shorts under $0.10. Sponsorships and affiliate income usually exceed AdSense once a channel passes ~50,000 subscribers.</p>'],
    ],
    table: T(['Monthly views', 'RPM', 'AdSense revenue', 'Hourly rate at 60 h/month'], [['100,000', '$2', '$200', '$3.33'], ['500,000', '$4', '$2,000', '$33'], ['1,000,000', '$4', '$4,000', '$67'], ['1,000,000', '$12', '$12,000', '$200']]),
    faqs: [
      ['How much does YouTube pay per 1,000 views?', 'Creators typically keep $1–$5 per 1,000 monetized views; finance and tech niches can reach $10–$20.'],
      ['What is the difference between CPM and RPM?', 'CPM is what advertisers pay per 1,000 ad impressions; RPM is what the creator receives per 1,000 video views after the platform&rsquo;s share.'],
      ['How do I calculate my YouTube hourly rate?', 'Divide monthly revenue by hours spent scripting, filming, editing, and publishing.'],
    ],
  },
  'calculators/tiktok-money-calculator-2026': {
    name: 'TikTok Creator Earnings Per Hour Calculator',
    title: 'TikTok Money Calculator 2026: Creator Fund Pay Per Hour | Worth',
    description: 'Estimate TikTok Creator Rewards income from views and turn it into an hourly rate. 2026 payout ranges, brand deal benchmarks, and a worked table.',
    intro: 'Enter monthly TikTok earnings and hours spent creating to see your real pay per hour.',
    keywords: ['tiktok money calculator', 'tiktok creator fund calculator', 'tiktok earnings per view'],
    sections: [
      ['Creator Rewards math', '<p><strong>Earnings ≈ qualified views ÷ 1,000 × RPM.</strong> The Creator Rewards Program pays roughly $0.40–$1.00 per 1,000 qualified views on videos over one minute. 2 million qualified views a month at $0.60 is $1,200.</p>'],
      ['Hourly rate reality', '<p>If those 2 million views come from 40 videos at 2 hours each, $1,200 ÷ 80 hours = $15 per hour. Brand deals change the picture: a creator with 100,000 followers commonly charges $500–$2,000 per sponsored post.</p>'],
      ['Comparing platforms', '<p>Per view, TikTok pays a fraction of long-form YouTube. Per hour of production, short vertical video can still win because each clip takes far less time. Measure both and compare in hours.</p>'],
    ],
    table: T(['Monthly qualified views', 'RPM', 'Program earnings', 'Hourly at 80 h/month'], [['500,000', '$0.50', '$250', '$3.13'], ['2,000,000', '$0.60', '$1,200', '$15'], ['5,000,000', '$0.80', '$4,000', '$50'], ['10,000,000', '$0.80', '$8,000', '$100']]),
    faqs: [
      ['How much does TikTok pay per 1,000 views?', 'Roughly $0.40 to $1.00 for qualified views under the Creator Rewards Program; Shorts-style clips under a minute usually earn nothing.'],
      ['How many followers do I need to earn on TikTok?', '10,000 followers and 100,000 views in the last 30 days for the rewards program; brand deals can start earlier.'],
      ['How do I calculate my TikTok hourly rate?', 'Total monthly earnings ÷ hours spent filming, editing, and posting.'],
    ],
  },
  'calculators/onlyfans-earnings-calculator-2026': {
    name: 'Creator Subscription Income Per Hour Calculator',
    title: 'OnlyFans Earnings Calculator 2026: Net Income Per Hour | Worth',
    description: 'Estimate subscription-platform income after the 20% platform fee and self-employment tax, then divide by hours worked. Formula, 2026 table, and tax notes.',
    intro: 'Enter monthly net creator income and hours worked to see the real hourly rate after fees and tax.',
    keywords: ['onlyfans earnings calculator', 'creator subscription income calculator', 'onlyfans hourly rate'],
    sections: [
      ['Gross to net', '<p><strong>Net = (subscribers × price + tips + PPV) × 0.80 − taxes.</strong> The platform keeps 20%. 300 subscribers at $9.99 gross $2,997; after the fee that is $2,398, and after roughly 30% combined income and self-employment tax, about $1,680.</p>'],
      ['Hours are the hidden cost', '<p>Content, messaging, and promotion commonly consume 30–60 hours a month. $1,680 ÷ 45 hours = $37 per hour. The median account earns under $200 a month, so run the numbers with your own subscriber count rather than headline figures.</p>'],
      ['Tax treatment', '<p>Creator income is self-employment income in the US: 15.3% SE tax on net profit plus ordinary income tax. Equipment, software, and a home-office share are deductible.</p>'],
    ],
    table: T(['Paid subscribers at $9.99', 'Gross', 'After 20% fee', 'After ~30% tax', 'Hourly at 45 h'], [['50', '$500', '$400', '$280', '$6.20'], ['300', '$2,997', '$2,398', '$1,680', '$37'], ['1,000', '$9,990', '$7,992', '$5,594', '$124'], ['5,000', '$49,950', '$39,960', '$27,972', '$622']]),
    faqs: [
      ['What percentage does OnlyFans take?', '20% of all earnings, including subscriptions, tips, and pay-per-view messages.'],
      ['Do creators pay self-employment tax?', 'Yes in the US: 15.3% on net profit in addition to income tax, filed on Schedule C.'],
      ['How is hourly income calculated?', 'Net after-tax income ÷ total hours spent producing content, messaging, and marketing.'],
    ],
  },
  'calculators/freelance-rate-calculator-2026': {
    name: 'Freelance Hourly Rate Calculator 2026',
    title: 'Freelance Rate Calculator 2026: Set Your Hourly Rate | Worth',
    description: 'Work out a freelance hourly rate from a target salary, billable hours, overhead and tax. 2026 formula, a rate table from $50k to $150k, and a day-rate conversion.',
    intro: 'Enter your target take-home income and expected billable hours to find the hourly rate you need to charge.',
    keywords: ['freelance rate calculator', 'freelance hourly rate 2026', 'how much to charge freelance'],
    sections: [
      ['The freelance rate formula', '<p><strong>Rate = (target salary + overhead + benefits) ÷ billable hours ÷ (1 − tax rate).</strong> Target $80,000, add $12,000 overhead and $8,000 benefits, divide by 1,200 billable hours, then gross up for a 30% tax rate: $100,000 ÷ 1,200 ÷ 0.70 ≈ $119 per hour.</p>'],
      ['Why 1,200 billable hours, not 2,080', '<p>Admin, sales, invoicing, learning, sick days, and gaps between clients eat 35–45% of a freelance year. Most full-time freelancers bill 1,000–1,400 hours.</p>'],
      ['Day rate and project pricing', '<p>Day rate = hourly × 7 or 8 with a small discount for commitment. Project price = estimated hours × rate × 1.2 contingency. Never quote a project below the hours it will really take at your minimum rate.</p>'],
    ],
    table: T(['Target take-home', 'Overhead + benefits', 'Billable hours', 'Rate at 30% tax'], [['$50,000', '$12,000', '1,200', '$74/h'], ['$80,000', '$20,000', '1,200', '$119/h'], ['$110,000', '$25,000', '1,300', '$148/h'], ['$150,000', '$30,000', '1,400', '$184/h']]),
    faqs: [
      ['How do I calculate my freelance hourly rate?', 'Add target salary, overhead, and benefits; divide by realistic billable hours; then divide by (1 − your tax rate).'],
      ['What is a good freelance rate in 2026?', 'Experienced developers and designers in the US typically charge $75–$200 per hour; writers and VAs $30–$90. Your rate should cover a comparable salary plus 30–50%.'],
      ['Should I charge hourly or per project?', 'Quote projects when scope is clear and you are fast; hourly when scope is open. Price both from the same underlying rate.'],
    ],
  },
  'calculators/rent-vs-buy-calculator-2026': {
    name: 'Rent vs Buy in Hours of Work Calculator',
    title: 'Rent vs Buy Calculator 2026: Monthly Cost in Work Hours | Worth',
    description: 'Compare renting and buying by the hours of work each costs per month. Full ownership cost formula, a 2026 table at 6.5% rates, and the break-even horizon.',
    intro: 'Enter the monthly cost of renting or owning and your hourly pay to compare both in hours of work.',
    keywords: ['rent vs buy calculator', 'rent or buy 2026', 'cost of owning vs renting'],
    sections: [
      ['Comparing like with like', '<p><strong>Ownership cost = mortgage interest + property tax + insurance + maintenance (≈1% of value per year) + HOA − tax benefit.</strong> Principal repayment is savings, not cost. Rent cost = rent + renter&rsquo;s insurance. Divide each by your take-home hourly pay.</p>'],
      ['A 2026 example', '<p>A $400,000 home with 10% down at 6.5% costs about $1,950 a month in interest early on, plus $500 tax, $150 insurance, and $330 maintenance: roughly $2,930 unrecoverable per month. Renting a similar home at $2,400 is cheaper by 18 hours a month at $30 per hour.</p>'],
      ['When buying wins', '<p>Ownership overtakes renting when appreciation and rent inflation outrun the extra unrecoverable cost, typically after 5–7 years in average markets. Shorter horizons usually favor renting once buying and selling costs (6–8%) are included.</p>'],
    ],
    table: T(['Scenario', 'Unrecoverable monthly cost', 'Hours at $30/hr'], [['Rent at $2,000', '$2,000', '67 h'], ['Rent at $2,400', '$2,400', '80 h'], ['Own $400k home (yr 1)', '$2,930', '98 h'], ['Own $300k home (yr 1)', '$2,200', '73 h']]),
    faqs: [
      ['Is it cheaper to rent or buy in 2026?', 'In most US metros renting is cheaper month to month at 6–7% mortgage rates; buying wins over 5+ years if prices and rents keep rising.'],
      ['What costs count as unrecoverable when owning?', 'Interest, property tax, insurance, maintenance, and HOA fees. Principal builds equity and is excluded.'],
      ['How do I compare rent and buy in hours?', 'Divide each monthly unrecoverable cost by your after-tax hourly pay and compare the two hour totals.'],
    ],
  },
  'calculators/car-loan-calculator-2026': {
    name: 'Car Payment in Hours of Work Calculator',
    title: 'Car Loan Calculator 2026: Payment in Hours of Work | Worth',
    description: 'Turn a car payment into hours of work per month. Loan payment formula, a 2026 table at 7% for 36–72 months, and the total interest cost in time.',
    intro: 'Enter your monthly car payment and take-home hourly pay to see how many hours a month the car takes.',
    keywords: ['car loan calculator', 'car payment in hours', 'auto loan 2026'],
    sections: [
      ['Payment to hours', '<p><strong>Hours per month = car payment ÷ take-home hourly pay.</strong> A $650 payment at $28 per hour is 23 hours a month, nearly three full working days before insurance, fuel, and parking.</p>'],
      ['Loan payment formula', '<p>Payment = L × r ÷ (1 − (1 + r)<sup>−n</sup>). $35,000 at 7% APR over 60 months is $693 a month and $6,580 in total interest, which is 235 hours of work at $28 per hour spent purely on borrowing.</p>'],
      ['Term length trade-off', '<p>Stretching from 60 to 72 months cuts the payment by about $95 but adds roughly $1,400 of interest and leaves you underwater longer. Compare the total hours, not just the monthly figure.</p>'],
    ],
    table: T(['$35,000 at 7% APR', 'Monthly payment', 'Total interest', 'Payment hours/month at $28'], [['36 months', '$1,081', '$3,910', '38.6 h'], ['48 months', '$838', '$5,230', '29.9 h'], ['60 months', '$693', '$6,580', '24.8 h'], ['72 months', '$597', '$7,960', '21.3 h']]),
    faqs: [
      ['How many hours of work should a car payment be?', 'A common rule keeps total car costs under 10–15% of take-home pay, roughly 17–26 hours of a 173-hour month.'],
      ['How is a car loan payment calculated?', 'Payment = loan × monthly rate ÷ (1 − (1 + monthly rate)^−months).'],
      ['Does a longer loan cost more?', 'Yes. Longer terms lower the payment but raise total interest, often by thousands of dollars.'],
    ],
  },
  'calculators/student-loan-calculator-2026': {
    name: 'Student Loan Payment in Work Hours Calculator',
    title: 'Student Loan Calculator 2026: Payment in Hours of Work | Worth',
    description: 'Convert a student loan payment into hours of work per month. Standard 10-year payment table at 2026 federal rates, total interest, and payoff time.',
    intro: 'Enter your monthly student loan payment and hourly pay to see how much of each working month goes to the loan.',
    keywords: ['student loan calculator', 'student loan payment hours of work', 'student loan payoff 2026'],
    sections: [
      ['Payment in hours', '<p><strong>Hours per month = loan payment ÷ take-home hourly pay.</strong> A $380 payment at $24 per hour is 15.8 hours a month, about two working days. Over a 10-year standard plan that is 1,900 hours in total.</p>'],
      ['2026 federal rates', '<p>Undergraduate direct loans for 2025–26 carry 6.39% interest; graduate loans 7.94%; PLUS loans 8.94%. A $30,000 balance at 6.39% over 10 years costs $338 a month and $10,600 in interest.</p>'],
      ['Faster payoff', '<p>Adding $100 a month to the $338 payment clears the loan in about 7.3 years and saves roughly $3,000 of interest, which is 125 hours of work returned to you.</p>'],
    ],
    table: T(['Balance at 6.39%, 10 yr', 'Monthly payment', 'Total interest', 'Hours/month at $24'], [['$15,000', '$169', '$5,300', '7.0 h'], ['$30,000', '$338', '$10,600', '14.1 h'], ['$50,000', '$564', '$17,600', '23.5 h'], ['$80,000', '$902', '$28,200', '37.6 h']]),
    faqs: [
      ['How much of my paycheck should go to student loans?', 'Under the standard plan most borrowers pay 8–12% of take-home pay; income-driven plans cap payments at 10% of discretionary income.'],
      ['How is a student loan payment calculated?', 'Same amortization formula as any fixed loan: balance × monthly rate ÷ (1 − (1 + monthly rate)^−months).'],
      ['Does paying extra help?', 'Yes. Extra payments reduce principal directly, cutting both the payoff time and total interest.'],
    ],
  },
  'calculators/net-worth-calculator-2026': {
    name: 'Net Worth in Hours of Work Calculator',
    title: 'Net Worth Calculator 2026: Wealth Measured in Work Hours | Worth',
    description: 'Calculate net worth (assets minus liabilities) and express it as hours of your own labor. 2026 US median net worth by age and a step-by-step worksheet.',
    intro: 'Enter your net worth and your hourly pay to see how many hours of work your wealth represents.',
    keywords: ['net worth calculator', 'net worth by age 2026', 'net worth in hours'],
    sections: [
      ['Net worth formula', '<p><strong>Net worth = total assets − total liabilities.</strong> Assets: cash, investments, retirement accounts, home equity, vehicles at resale value. Liabilities: mortgage, loans, card balances. $180,000 in assets minus $120,000 owed is $60,000.</p>'],
      ['Hours of freedom', '<p>Divide net worth by your take-home hourly pay: $60,000 ÷ $30 = 2,000 hours, almost one full working year. Some people call this &ldquo;hours of runway&rdquo;: how long you could stop trading time for money if spending matched income.</p>'],
      ['Benchmarks', '<p>The 2022 Federal Reserve survey put US median household net worth at $192,700, with medians of $39,000 under 35 and $364,500 for ages 55–64. Averages are far higher because of the top 10%. Compare against the median for your age, not the mean.</p>'],
    ],
    table: T(['Age group', 'US median net worth (SCF 2022)', 'Hours at $30/hr'], [['Under 35', '$39,000', '1,300 h'], ['35–44', '$135,600', '4,520 h'], ['45–54', '$247,200', '8,240 h'], ['55–64', '$364,500', '12,150 h']]),
    faqs: [
      ['How do I calculate my net worth?', 'Add everything you own at current value and subtract everything you owe.'],
      ['What is a good net worth by age?', 'Median US household net worth is about $39,000 under 35 and $364,500 at 55–64; a common target is 1× salary by 30 and 3× by 40.'],
      ['Why measure net worth in hours?', 'It converts an abstract balance into time: 2,000 hours of net worth is one year of work you would not need to do.'],
    ],
  },
  'calculators/cost-of-living-calculator-2026': {
    name: 'Cost of Living in Hours of Work Calculator',
    title: 'Cost of Living Calculator 2026: Monthly Costs in Work Hours | Worth',
    description: 'Compare cities by how many hours of work a month of living costs at local wages. 2026 rent and cost index table for six US cities and a relocation formula.',
    intro: 'Enter your monthly essential costs and hourly pay to see how many hours it takes to cover a month of living where you are.',
    keywords: ['cost of living calculator', 'cost of living by city 2026', 'cost of living in hours'],
    sections: [
      ['Hours to cover a month', '<p><strong>Hours = monthly essentials ÷ take-home hourly pay.</strong> Essentials in Austin at $3,400 on $32 per hour take 106 hours; in San Francisco $5,200 on $45 takes 116 hours. The higher salary does not fully offset the higher cost.</p>'],
      ['Relocation formula', '<p>Equivalent salary = current salary × (new cost index ÷ current cost index). Moving from a city indexed at 100 to one at 140 needs a 40% raise just to stand still. Ask for the hourly figure, then divide new rent into it.</p>'],
      ['What to include', '<p>Rent or mortgage, utilities, groceries, transport, insurance, childcare. Leave out discretionary spending so the comparison measures the floor, not lifestyle.</p>'],
    ],
    table: T(['City', 'Typical 1-bed rent 2026', 'Essentials/month', 'Hours at local median net pay'], [['Houston', '$1,300', '$2,900', '104 h at $28'], ['Austin', '$1,500', '$3,400', '106 h at $32'], ['Chicago', '$1,900', '$3,800', '112 h at $34'], ['New York', '$3,600', '$5,600', '124 h at $45'], ['San Francisco', '$3,200', '$5,200', '116 h at $45']]),
    faqs: [
      ['How do I compare cost of living between cities?', 'Divide each city&rsquo;s monthly essential costs by the take-home hourly pay you would earn there; fewer hours means more room in the budget.'],
      ['How much more salary do I need to move to an expensive city?', 'Multiply your salary by the ratio of the two cost indexes; a 100 → 140 move needs about 40% more.'],
      ['What counts as essential costs?', 'Housing, utilities, food, transport, insurance, and childcare.'],
    ],
  },
  'calculators/salary-in-hours-elon-musk-calculator': {
    name: 'Your Purchases in Elon Musk Time Calculator',
    title: 'Elon Musk Salary Per Second: Your Purchases in Musk Time | Worth',
    description: 'Compare what a purchase costs you in hours with what it costs Elon Musk in seconds, based on 2026 net worth growth. Formula and a side-by-side table.',
    intro: 'Enter a price and your hourly pay. The result is your hours; the table below shows the same price in billionaire seconds.',
    keywords: ['elon musk salary per second', 'elon musk earnings per hour', 'billionaire time calculator'],
    sections: [
      ['How &ldquo;per second&rdquo; figures are calculated', '<p><strong>Earnings per second = annual net worth change ÷ 31,536,000 seconds.</strong> Musk&rsquo;s net worth rose roughly $200 billion across 2024, about $6,340 per second on paper. It is unrealized stock value, not salary; in 2025 the same math ran negative for months.</p>'],
      ['Your purchases on both clocks', '<p>At $30 per hour a $1,200 laptop is 40 hours of your work. At $6,340 per second it is under a fifth of a second. The comparison is not about envy; it shows why prices mean different things at different incomes.</p>'],
      ['A fairer comparison', '<p>Median US household income is about $80,000, or roughly $38 an hour gross. Compare yourself with medians for your job and city rather than with a founder&rsquo;s share price.</p>'],
    ],
    table: T(['Purchase', 'Your hours at $30/hr', 'Musk seconds at $6,340/s'], [['Coffee $5', '10 min', '0.0008 s'], ['Laptop $1,200', '40 h', '0.19 s'], ['Car $35,000', '1,167 h', '5.5 s'], ['House $400,000', '13,333 h', '63 s']]),
    faqs: [
      ['How much does Elon Musk make per second?', 'Using 2024 net worth growth of about $200 billion, roughly $6,300 per second; the number swings with Tesla and SpaceX valuations and can be negative.'],
      ['Is that salary?', 'No. It is a change in stock value. His formal salary at Tesla has been $0 for years.'],
      ['How do I compare my purchase in hours?', 'Divide the price by your take-home hourly pay.'],
    ],
  },
  'calculators/wedding-budget-calculator-2026': {
    name: 'Wedding Cost in Hours of Work Calculator',
    title: 'Wedding Budget Calculator 2026: Cost in Hours of Work | Worth',
    description: 'Turn a wedding budget into the hours of work it takes to pay for it. 2026 average cost breakdown by category, per-guest math, and a savings timeline.',
    intro: 'Enter your wedding budget and combined hourly pay to see how many working hours the day costs.',
    keywords: ['wedding budget calculator', 'average wedding cost 2026', 'wedding cost in hours'],
    sections: [
      ['Budget to hours', '<p><strong>Hours = total wedding cost ÷ combined take-home hourly pay.</strong> The average US wedding ran about $33,000 in 2025. For a couple earning $55 per hour after tax together, that is 600 hours, or 15 weeks of both people&rsquo;s full-time work.</p>'],
      ['Per-guest cost', '<p>Venue, catering, and bar scale with the guest list at roughly $150–$300 per person. Cutting 30 guests from 130 saves $4,500–$9,000, or 80–160 hours of work.</p>'],
      ['Saving for it', '<p>Months to save = cost ÷ monthly savings. $33,000 at $1,500 a month is 22 months. Dividing the plan into categories keeps any one line, usually catering at 40–50%, from swallowing the rest.</p>'],
    ],
    table: T(['Category', 'Share of $33,000', 'Cost', 'Hours at $55/hr (couple)'], [['Venue + catering', '45%', '$14,850', '270 h'], ['Photography + video', '12%', '$3,960', '72 h'], ['Attire + rings', '12%', '$3,960', '72 h'], ['Music, flowers, décor', '18%', '$5,940', '108 h'], ['Everything else', '13%', '$4,290', '78 h']]),
    faqs: [
      ['What does the average wedding cost in 2026?', 'Roughly $33,000 in the US excluding the honeymoon; medians are lower, around $10,000–$15,000.'],
      ['How much does each wedding guest cost?', 'Typically $150–$300 once venue, food, drinks, rentals, and invitations are included.'],
      ['How do I turn a wedding budget into hours?', 'Divide the total by the couple&rsquo;s combined after-tax hourly pay.'],
    ],
  },
  'calculators/lottery-tax-calculator-2026': {
    name: 'Lottery Winnings After Tax in Work Hours',
    title: 'Lottery Tax Calculator 2026: Take-Home Jackpot in Work Hours | Worth',
    description: 'See what a lottery prize is worth after federal and state tax, lump sum versus annuity, and how many years of work the net amount replaces.',
    intro: 'Enter the after-tax lump sum and your hourly pay to see how many working hours the prize replaces.',
    keywords: ['lottery tax calculator', 'powerball after tax 2026', 'lottery lump sum vs annuity'],
    sections: [
      ['From jackpot to bank account', '<p><strong>Net lump sum ≈ advertised jackpot × ~0.50 cash value × (1 − 0.37 federal − state rate).</strong> A $100 million advertised Powerball has a cash value near $48 million; after 37% federal tax and, say, 5% state tax, about $28 million reaches you.</p>'],
      ['Lump sum or annuity', '<p>The annuity pays the full advertised figure over 30 years, rising 5% annually, and is taxed each year. Lump sum wins if you can invest at more than roughly 4–5% after tax; annuity wins on discipline.</p>'],
      ['Years of work replaced', '<p>$28 million ÷ $30 per hour = 933,000 hours, about 450 working years. Even a $1 million prize nets around $600,000 after tax: 20,000 hours, or ten years of full-time work.</p>'],
    ],
    table: T(['Advertised jackpot', 'Cash value (≈52%)', 'After 37% federal + 5% state', 'Working years at $30/hr'], [['$1,000,000', '$1,000,000*', '$580,000', '9.3 yr'], ['$20,000,000', '$10,400,000', '$6,030,000', '97 yr'], ['$100,000,000', '$52,000,000', '$30,160,000', '483 yr'], ['$500,000,000', '$260,000,000', '$150,800,000', '2,417 yr']]),
    faqs: [
      ['How much tax is taken from lottery winnings?', 'The US withholds 24% federal upfront, but prizes this size land in the 37% bracket; most states add 0–10.9%.'],
      ['Is lump sum or annuity better?', 'Lump sum offers control and typically more if invested well; the annuity protects against overspending and locks in the full advertised amount.'],
      ['Why convert winnings to hours of work?', 'It shows the scale honestly: a $1 million prize is about ten years of median-wage work after tax, not a lifetime.'],
    ],
  },
  'calculators/divorce-cost-calculator-2026': {
    name: 'Divorce Cost in Hours of Work Calculator',
    title: 'Divorce Cost Calculator 2026: Legal Fees in Hours of Work | Worth',
    description: 'Estimate divorce costs by route (uncontested, mediated, litigated) and convert legal fees into hours of your own work. 2026 US cost table and fee drivers.',
    intro: 'Enter an estimated total divorce cost and your hourly pay to see the hours of work it represents.',
    keywords: ['divorce cost calculator', 'average cost of divorce 2026', 'divorce legal fees'],
    sections: [
      ['What divorce costs in 2026', '<p><strong>Cost = attorney hours × hourly rate + filing fees + expert fees.</strong> Uncontested filings with online forms run $300–$1,500. Mediation typically $3,000–$8,000. Litigated cases with children or property disputes average $15,000–$30,000 per spouse and can pass $100,000.</p>'],
      ['In hours of work', '<p>A $20,000 litigated divorce at $30 per hour after tax is 667 hours, four months of full-time work. Attorneys bill $250–$500 per hour, so each hour you argue costs you 8–17 hours of your own labor.</p>'],
      ['Lowering the bill', '<p>Agree on as much as possible before involving lawyers, use mediation for the rest, and keep communication in writing to reduce billable back-and-forth. Every avoided attorney hour is roughly a working day saved.</p>'],
    ],
    table: T(['Route', 'Typical cost per spouse', 'Hours at $30/hr'], [['DIY uncontested', '$500', '17 h'], ['Mediated', '$6,000', '200 h'], ['Collaborative', '$12,000', '400 h'], ['Litigated with children', '$25,000', '833 h']]),
    faqs: [
      ['How much does a divorce cost in 2026?', 'From a few hundred dollars for an uncontested filing to $15,000–$30,000 per spouse for a contested case.'],
      ['What makes divorce expensive?', 'Disputes over custody, property, or support that require attorney time, expert valuations, and court appearances.'],
      ['How do I convert legal fees to hours of work?', 'Divide the total fee by your after-tax hourly pay.'],
    ],
  },
  'calculators/child-cost-calculator-2026': {
    name: 'Cost of Raising a Child in Work Hours',
    title: 'Child Cost Calculator 2026: Raising a Kid in Hours of Work | Worth',
    description: 'Convert the monthly cost of a child into hours of work. 2026 cost estimates by age from USDA-based figures, childcare share, and total to age 18.',
    intro: 'Enter your monthly child-related spending and hourly pay to see how many working hours a month go to your kid.',
    keywords: ['cost of raising a child 2026', 'child cost calculator', 'childcare cost per month'],
    sections: [
      ['Monthly cost to hours', '<p><strong>Hours = monthly child costs ÷ take-home hourly pay.</strong> The USDA&rsquo;s inflation-adjusted estimate for a middle-income family is about $1,500 per month per child, or 50 hours a month at $30 per hour: more than a full working week.</p>'],
      ['Total to age 18', '<p>$1,500 × 12 × 18 ≈ $324,000 before college. In hours that is 10,800, or 5.2 working years. Childcare dominates ages 0–4 at $1,000–$2,500 a month in most metros; housing and food dominate later.</p>'],
      ['What shifts the number', '<p>Second children cost roughly 25% less each through shared housing and hand-me-downs. Location, childcare choice, and whether one parent reduces hours matter more than any spending tactic.</p>'],
    ],
    table: T(['Age band', 'Typical monthly cost', 'Hours/month at $30/hr'], [['0–2 (with daycare)', '$2,300', '77 h'], ['3–5 (with preschool)', '$2,000', '67 h'], ['6–11', '$1,300', '43 h'], ['12–17', '$1,500', '50 h']]),
    faqs: [
      ['How much does it cost to raise a child in 2026?', 'Roughly $300,000–$330,000 to age 18 for a middle-income US family, about $1,500 a month on average.'],
      ['What is the biggest expense?', 'Housing overall, and childcare during the first five years.'],
      ['How do I measure child costs in hours?', 'Divide monthly child-related spending by your after-tax hourly pay.'],
    ],
  },
  'calculators/streaming-cost-calculator-2026': {
    name: 'Streaming Bundle Cost in Work Hours 2026',
    title: 'Streaming Cost Calculator 2026: All Services in Work Hours | Worth',
    description: 'Add up 2026 streaming prices (Netflix, Disney+, Max, Spotify and more) and convert the yearly total into hours of work. Price table and cut-list method.',
    intro: 'Enter your combined monthly streaming spend and hourly pay to see the yearly cost in hours of work.',
    keywords: ['streaming cost calculator 2026', 'how much do streaming services cost', 'netflix price 2026'],
    sections: [
      ['Yearly cost in hours', '<p><strong>Hours per year = monthly total × 12 ÷ take-home hourly pay.</strong> Five services at $78 a month total $936 a year, or 31 hours at $30 per hour, nearly four working days for television.</p>'],
      ['2026 price check', '<p>Ad-free tiers now cluster at $16–$20: Netflix Standard $17.99, Disney+ Premium $18.99, Max $18.49, Spotify Premium $11.99, YouTube Premium $13.99. Ad-supported plans run $8–$10 and roughly halve the bill.</p>'],
      ['Cut list method', '<p>Sort services by hours watched last month. Divide each fee by its hours to get a cost per viewing hour; anything above $3 per hour is a rotation candidate. Subscribe for a month, binge, cancel.</p>'],
    ],
    table: T(['Service (2026, ad-free)', 'Monthly', 'Yearly', 'Hours/year at $30/hr'], [['Netflix Standard', '$17.99', '$216', '7.2 h'], ['Disney+ Premium', '$18.99', '$228', '7.6 h'], ['Max', '$18.49', '$222', '7.4 h'], ['Spotify Premium', '$11.99', '$144', '4.8 h'], ['All four', '$67.46', '$810', '27 h']]),
    faqs: [
      ['How much do streaming services cost per year in 2026?', 'A typical household with four or five services pays $800–$1,000 a year on ad-free tiers.'],
      ['How do I calculate cost per hour watched?', 'Divide the monthly fee by hours watched that month; $18 for 6 hours is $3 per hour.'],
      ['What is the cheapest way to keep streaming?', 'Ad-supported tiers and rotating one or two services at a time instead of holding all of them.'],
    ],
  },
  'calculators/chatgpt-cost-calculator-2026': {
    name: 'AI Subscription Cost in Work Hours Calculator',
    title: 'ChatGPT Cost Calculator 2026: AI Subscriptions in Work Hours | Worth',
    description: 'Compare ChatGPT Plus, Pro, Claude, Gemini and Copilot prices in hours of work per year, and check whether the time an AI tool saves covers its cost.',
    intro: 'Enter your monthly AI subscription spend and hourly pay to see the yearly cost in hours, then compare it with the hours the tools save you.',
    keywords: ['chatgpt cost calculator', 'chatgpt plus price 2026', 'ai subscription cost'],
    sections: [
      ['Cost in hours', '<p><strong>Hours per year = monthly fee × 12 ÷ take-home hourly pay.</strong> ChatGPT Plus at $20 is $240 a year, 8 hours at $30 per hour. ChatGPT Pro at $200 is $2,400 a year, 80 hours: two full working weeks.</p>'],
      ['The break-even test', '<p>A subscription pays for itself when hours saved per month × your hourly value > monthly fee. At $30 per hour, Plus needs to save 40 minutes a month; Pro needs to save nearly 7 hours a month. For most people Plus clears the bar easily and Pro does not.</p>'],
      ['API instead of subscription', '<p>Light users often spend under $5 a month on API pricing. Heavy daily users, or anyone who values the app interface, usually do better on a flat plan.</p>'],
    ],
    table: T(['Plan (2026)', 'Monthly', 'Yearly', 'Hours/year at $30/hr', 'Minutes/month to break even'], [['ChatGPT Plus', '$20', '$240', '8 h', '40 min'], ['Claude Pro', '$20', '$240', '8 h', '40 min'], ['Gemini AI Pro', '$19.99', '$240', '8 h', '40 min'], ['ChatGPT Pro', '$200', '$2,400', '80 h', '6.7 h']]),
    faqs: [
      ['How much does ChatGPT cost in 2026?', 'Free tier, Plus at $20 a month, Pro at $200 a month; Team and Enterprise are priced per seat.'],
      ['Is ChatGPT Plus worth it?', 'If it saves you more than about 40 minutes a month at a $30 hourly value, yes on pure arithmetic.'],
      ['Should I pay per token instead?', 'API pay-as-you-go is cheaper for occasional use; flat plans win for daily heavy use.'],
    ],
  },
  'calculators/mrbeast-earnings-per-second-calculator': {
    name: 'MrBeast Earnings Per Second vs Your Pay',
    title: 'MrBeast Earnings Per Second Calculator: Compared to Your Pay | Worth',
    description: 'Estimate MrBeast\u2019s 2026 income per second, hour, and day from reported revenue, and compare with your own hourly pay using the calculator.',
    intro: 'Enter a price and your hourly pay to see your hours; the table below shows the same purchase in MrBeast seconds.',
    keywords: ['mrbeast earnings per second', 'how much does mrbeast make', 'mrbeast net worth 2026'],
    sections: [
      ['Estimating creator income per second', '<p><strong>Per second = annual revenue ÷ 31,536,000.</strong> Beast Industries reported about $473 million of revenue in 2024 with a stated goal of more than $1 billion for 2025. Revenue is not personal income; the company reinvests heavily and has posted losses. Even at $100 million of personal earnings the figure is about $3.17 per second, $11,400 per hour.</p>'],
      ['Where the money comes from', '<p>YouTube AdSense is a minority. Feastables snacks, Lunchly, brand sponsorships, and the Amazon show contribute far more. Videos with $1–$5 million budgets are financed by those streams, which is why per-view math understates the business.</p>'],
      ['Your purchases on his clock', '<p>At $11,400 per hour, a $1,200 laptop is 6.3 minutes. At $30 per hour it is 40 hours. Use the comparison to put creator headlines in proportion, not as a benchmark.</p>'],
    ],
    table: T(['Purchase', 'Your hours at $30/hr', 'MrBeast time at $11,400/hr'], [['Coffee $5', '10 min', '1.6 s'], ['Laptop $1,200', '40 h', '6.3 min'], ['Car $35,000', '1,167 h', '3.1 h'], ['House $400,000', '13,333 h', '35 h']]),
    faqs: [
      ['How much does MrBeast make per second?', 'Estimates based on $100 million of personal annual earnings give about $3 per second; company revenue is several times higher but is not his salary.'],
      ['How much did Beast Industries make?', 'Reported revenue of roughly $473 million in 2024, with a target above $1 billion for 2025.'],
      ['How do I compare my own pay?', 'Divide any price by your after-tax hourly pay to get your hours.'],
    ],
  },
  'calculators/side-hustle-calculator-2026': {
    name: 'Side Hustle Real Hourly Rate Calculator',
    title: 'Side Hustle Calculator 2026: Real Hourly Rate After Costs | Worth',
    description: 'Find the true hourly rate of a side hustle after expenses, taxes and unpaid time. 2026 table for delivery, rideshare, tutoring and freelancing, plus a break-even check.',
    intro: 'Enter your monthly side income after expenses and total hours (including unpaid setup) to see the real hourly rate.',
    keywords: ['side hustle calculator', 'side hustle hourly rate', 'is my side hustle worth it'],
    sections: [
      ['The real hourly rate', '<p><strong>Real rate = (revenue − expenses − tax) ÷ (paid hours + unpaid hours).</strong> Delivery driving that grosses $800 a month over 40 app hours looks like $20 per hour. Subtract $180 of fuel and wear, 25% tax, and 8 hours of waiting and admin, and it is $465 ÷ 48 = $9.70 per hour.</p>'],
      ['Compare against your main job', '<p>If your day-job take-home is $28 per hour and overtime or a raise is possible, a $9.70 hustle is a poor trade for the same hour. Hustles with low costs and repeat clients (tutoring, bookkeeping, specialized freelancing) usually clear $30–$60 real.</p>'],
      ['Tax note', '<p>US self-employment income over $400 owes 15.3% SE tax plus income tax; quarterly estimates avoid penalties. Track mileage: the 2025 IRS rate is 70 cents per mile.</p>'],
    ],
    table: T(['Side hustle', 'Gross/hour', 'Costs + 25% tax', 'Unpaid time', 'Real rate'], [['Food delivery', '$20', '$9', '20%', '$9.70'], ['Rideshare', '$24', '$12', '15%', '$10.40'], ['Online tutoring', '$35', '$9', '10%', '$23.60'], ['Freelance design', '$60', '$16', '30%', '$33.80']]),
    faqs: [
      ['How do I calculate my side hustle hourly rate?', 'Subtract expenses and tax from revenue, then divide by every hour spent including unpaid setup, travel, and admin.'],
      ['Is a side hustle worth it?', 'Compare its real hourly rate with what an extra hour at your main job, or an hour of rest, is worth to you.'],
      ['Do I pay tax on side income?', 'Yes. In the US, net self-employment income above $400 is taxable and subject to self-employment tax.'],
    ],
  },
  'calculators/ai-job-replacement-calculator-2026': {
    name: 'AI Task Automation Hours Calculator',
    title: 'AI Job Replacement Calculator 2026: Hours Automatable in Your Job | Worth',
    description: 'Estimate how many hours of your work week AI could automate, what those hours are worth, and how to redirect them. Task-level method with 2026 research figures.',
    intro: 'Enter the value of the hours AI could take over each month (hours × your pay) to see what that time is worth, then decide what to do with it.',
    keywords: ['ai job replacement calculator', 'will ai take my job', 'ai automation hours'],
    sections: [
      ['Task-level, not job-level', '<p><strong>Automatable hours = Σ (hours per task × automation share).</strong> Studies from 2023–2025 (Goldman Sachs, Pew, Microsoft) suggest 25–30% of current work hours in exposed occupations could be automated or heavily assisted, but almost no job is 100% tasks. List your weekly tasks and rate each 0–100%.</p>'],
      ['What the hours are worth', '<p>If 10 of your 40 weekly hours are drafting, summarizing, and data entry at 70% automatable, that is 7 hours a week, 30 a month. At $30 per hour it is $900 a month of labor value freed or displaced, depending on who captures it.</p>'],
      ['Redirecting the time', '<p>Workers who keep the value are the ones who move freed hours into tasks AI does poorly: judgment, relationships, physical work, accountability. Track your own ratio quarterly; it is a better signal than headlines.</p>'],
    ],
    table: T(['Task type', 'Typical automation share (2026)', 'On 10 h/week', 'Monthly value at $30/hr'], [['Data entry, formatting', '80%', '8 h', '$1,040'], ['Drafting emails, summaries', '60%', '6 h', '$780'], ['Analysis and research', '40%', '4 h', '$520'], ['Meetings, negotiation, care', '10%', '1 h', '$130']]),
    faqs: [
      ['Will AI replace my job?', 'For most jobs AI changes the task mix rather than eliminating the role; roughly a quarter of hours in exposed occupations are automatable today.'],
      ['How do I estimate my exposure?', 'List weekly tasks, estimate hours and an automation percentage for each, and sum the products.'],
      ['What should I do with freed hours?', 'Shift into judgment-heavy, relationship-heavy, or physical tasks and learn to direct the tools.'],
    ],
  },
  'calculators/trump-tariff-calculator-2026': {
    name: 'Tariff Cost Per Household in Work Hours',
    title: 'Tariff Calculator 2026: What Tariffs Cost You in Hours of Work | Worth',
    description: 'Estimate the extra yearly cost of 2025–2026 US tariffs for your household and convert it into hours of work. Formula, price pass-through, and an example table.',
    intro: 'Enter your estimated yearly tariff cost and hourly pay to see how many hours of work import taxes take from you.',
    keywords: ['tariff calculator', 'trump tariffs cost per household', 'tariff cost 2026'],
    sections: [
      ['How tariffs reach your receipt', '<p><strong>Extra cost = import price × tariff rate × pass-through share.</strong> Tariffs are paid by importers and mostly passed to consumers; studies of the 2018–2019 rounds found pass-through near 100% for many goods. A $1,000 imported appliance under a 25% tariff with 90% pass-through costs $225 more.</p>'],
      ['Household estimates', '<p>Independent 2025 estimates of the average household cost of the tariff schedule ranged from roughly $1,200 to $2,400 a year depending on which rates held. At $30 per hour after tax, that is 40–80 hours of work: one to two weeks.</p>'],
      ['Estimate your own', '<p>Add up yearly spending on imported goods (electronics, clothing, cars, furniture, toys), apply the applicable rate for each category, and enter the total above. Spending mix matters: households that buy more goods than services feel more of it.</p>'],
    ],
    table: T(['Household spend on imports', 'Average effective tariff', 'Yearly extra cost', 'Hours at $30/hr'], [['$5,000', '15%', '$675 (90% pass-through)', '22.5 h'], ['$10,000', '15%', '$1,350', '45 h'], ['$10,000', '25%', '$2,250', '75 h'], ['$20,000', '20%', '$3,600', '120 h']]),
    faqs: [
      ['Who pays tariffs?', 'Importers pay at the border and pass most of the cost to consumers through prices.'],
      ['How much do 2026 tariffs cost the average household?', 'Estimates cluster around $1,200–$2,400 a year depending on which rates are in force and how much a household spends on imported goods.'],
      ['How do I convert tariff cost to hours?', 'Divide your estimated yearly extra cost by your after-tax hourly pay.'],
    ],
  },
  'calculators/taylor-swift-concert-cost-calculator': {
    name: 'Concert Ticket Cost in Hours of Work',
    title: 'Concert Cost Calculator: Taylor Swift Tickets in Hours of Work | Worth',
    description: 'Convert concert tickets, fees, travel and merch into hours of work. Eras Tour price benchmarks, a full trip cost table, and a cost-per-hour-of-show check.',
    intro: 'Enter the all-in cost of a concert trip and your hourly pay to see how many working hours the night costs.',
    keywords: ['taylor swift ticket cost', 'concert cost calculator', 'eras tour ticket price'],
    sections: [
      ['All-in cost, not face value', '<p><strong>Trip cost = tickets + fees + travel + hotel + food + merch.</strong> Eras Tour face values ran $49–$449, but resale averaged $1,000–$2,500 and the average attendee spent about $1,300 on the full trip. At $30 per hour that is 43 hours of work for a three-hour show.</p>'],
      ['Cost per hour of show', '<p>Divide total cost by show length. $1,300 ÷ 3.5 hours = $371 per hour of music, or 12 working hours for every hour in the stadium. Comparing that to a $20 movie ($10 per hour) clarifies what you are buying: the experience, not the time.</p>'],
      ['Making it cheaper', '<p>Face-value resale queues, weekday or secondary-city dates, driving instead of flying, and skipping the $80 hoodie each cut the total by 10–40%. Decide the hours budget first, then fit the trip into it.</p>'],
    ],
    table: T(['Line item', 'Typical 2026 cost', 'Hours at $30/hr'], [['Ticket (resale, lower bowl)', '$900', '30 h'], ['Fees', '$150', '5 h'], ['Travel + hotel (1 night)', '$400', '13 h'], ['Merch + food', '$150', '5 h'], ['Total', '$1,600', '53 h']]),
    faqs: [
      ['How much do Taylor Swift tickets cost?', 'Face value $49–$449 on the Eras Tour; resale prices commonly ran $1,000–$2,500 and higher for floor seats.'],
      ['What did fans spend in total?', 'Surveys put the average all-in trip cost near $1,300 including travel, lodging, and merch.'],
      ['How do I decide if a concert is worth it?', 'Convert the all-in cost to hours of work and compare with other things you would do with those hours.'],
    ],
  },
  'guides/how-much-house-can-i-afford-2026': {
    name: 'How Much House Can I Afford in 2026?',
    title: 'How Much House Can I Afford in 2026? Rules, Rates, Examples | Worth',
    description: 'Work out a 2026 home budget with the 28/36 rule, current 6–7% rates, and a salary-to-price table. Includes the payment-in-hours check most calculators skip.',
    intro: 'A practical answer using the 28/36 rule, 2026 mortgage rates, and your take-home pay in hours.',
    keywords: ['how much house can i afford', 'home affordability 2026', '28/36 rule'],
    sections: [
      ['The 28/36 rule', '<p><strong>Housing payment ≤ 28% of gross monthly income; all debt ≤ 36%.</strong> On $90,000 a year, gross monthly income is $7,500, so the housing cap is $2,100 and total debt cap $2,700. Lenders sometimes stretch to 43–50% debt-to-income, which is how people end up house-poor.</p>'],
      ['From payment to price at 2026 rates', '<p>At 6.5% over 30 years each $100,000 borrowed costs about $632 a month in principal and interest. With $500 for tax and insurance inside the $2,100 cap, $1,600 of P&I supports roughly $253,000 of loan. Add a 10% down payment and the price ceiling is about $280,000.</p>'],
      ['The hours check', '<p>Divide the full payment by take-home hourly pay: $2,100 ÷ $32 = 66 hours a month, 38% of a working month. If that number makes you wince, the rule is not the problem; the price is. Run it before you fall for a listing.</p>'],
      ['Other costs that shrink the budget', '<p>Closing costs of 2–5%, moving, immediate repairs, and 1% of value per year in maintenance. Keep three to six months of payments in reserve after closing.</p>'],
    ],
    table: T(['Gross salary', '28% housing cap', 'Approx. max price (6.5%, 10% down)', 'Payment hours at net pay'], [['$60,000', '$1,400', '$175,000', '61 h at $23'], ['$90,000', '$2,100', '$280,000', '66 h at $32'], ['$120,000', '$2,800', '$385,000', '68 h at $41'], ['$180,000', '$4,200', '$600,000', '72 h at $58']]),
    faqs: [
      ['How much house can I afford on $90,000 a year?', 'Roughly $260,000–$300,000 at 2026 rates with 10% down and modest other debt, using the 28% rule.'],
      ['What is the 28/36 rule?', 'Spend at most 28% of gross income on housing and 36% on all debt combined.'],
      ['Should I use gross or net income?', 'Lenders use gross; you should sanity-check with net pay in hours, since that is what you actually live on.'],
    ],
  },
  'guides/are-you-rich-net-worth-percentile-2026': {
    name: 'Are You Rich? Net Worth and Income Percentiles 2026',
    title: 'Are You Rich? US Net Worth & Income Percentiles 2026 | Worth',
    description: 'See where your income and net worth rank against US households in 2026, why median and average differ so much, and how to measure wealth in hours of work.',
    intro: 'Percentile tables for US income and net worth, with the numbers translated into hours of work.',
    keywords: ['am i rich', 'net worth percentile 2026', 'income percentile calculator'],
    sections: [
      ['Income percentiles', '<p>Household income around <strong>$80,000</strong> is the US median. About $150,000 reaches the top 20%, $235,000 the top 10%, and roughly $600,000 the top 1%. Individual figures are lower: a single earner at $100,000 is already in the top 20% of workers.</p>'],
      ['Net worth percentiles', '<p>Median household net worth is about <strong>$193,000</strong>; the top 10% starts near $1.9 million and the top 1% around $13 million. The average, $1.06 million, is pulled up by the top; almost two thirds of households are below it.</p>'],
      ['Rich in hours', '<p>Divide net worth by take-home hourly pay. The median household at $193,000 and $35 per hour holds about 5,500 hours, under three working years. The top 10% at $1.9 million holds 54,000 hours, 26 years. That is the real definition of rich: years you no longer have to work.</p>'],
      ['Feeling rich versus being rich', '<p>Surveys find most people at the 90th percentile do not consider themselves wealthy, because comparison runs upward. Use the percentile tables to anchor to the distribution, then use the hours figure to anchor to your own life.</p>'],
    ],
    table: T(['Percentile', 'Household income (2026 est.)', 'Household net worth', 'Net worth in hours at $35/hr'], [['50th (median)', '$80,000', '$193,000', '5,500 h'], ['80th', '$150,000', '$800,000', '22,900 h'], ['90th', '$235,000', '$1,900,000', '54,300 h'], ['99th', '$600,000', '$13,000,000', '371,000 h']]),
    faqs: [
      ['What income is considered rich in the US?', 'Top 10% household income starts around $235,000; top 1% around $600,000.'],
      ['What net worth puts you in the top 10%?', 'About $1.9 million per household, based on the Federal Reserve Survey of Consumer Finances adjusted to 2026.'],
      ['Why is average net worth so much higher than median?', 'A small number of very wealthy households pull the average up; the median describes the typical household.'],
    ],
  },
  'guides/calculadora-hipoteca-2026-espana-mexico': {
    lang: 'es',
    name: 'Calculadora de hipoteca 2026: cuota en horas de trabajo',
    title: 'Calculadora de hipoteca 2026 (España y México): cuota en horas | Worth',
    description: 'Calcula la cuota de tu hipoteca en 2026 y conviértela en horas de trabajo. Fórmula, tabla con tipos del 3% al 11% para España y México, y el límite del 30–35%.',
    intro: 'Convierte la cuota mensual de una hipoteca en horas de trabajo con tu sueldo neto por hora.',
    keywords: ['calculadora hipoteca', 'calculadora hipoteca 2026', 'cuota hipoteca horas de trabajo'],
    sections: [
      ['Fórmula de la cuota', '<p><strong>Cuota = C × i ÷ (1 − (1 + i)<sup>−n</sup>)</strong>, donde C es el capital, i el tipo mensual y n el número de cuotas. Una hipoteca de 200.000 € a 30 años al 3,2% TIN (típica en España en 2026) tiene una cuota de unos 865 €. En México, un crédito de 2.000.000 MXN a 20 años al 10,5% ronda 19.970 MXN al mes.</p>'],
      ['La cuota en horas de trabajo', '<p><strong>Horas al mes = cuota ÷ salario neto por hora.</strong> Con un neto de 12 €/hora, 865 € son 72 horas: casi la mitad de un mes de 160 horas. En México, con 95 MXN/hora netos, 19.970 MXN son 210 horas, más que la jornada mensual completa; por eso la mayoría de créditos allí exigen ingresos familiares combinados.</p>'],
      ['El límite del 30–35 %', '<p>Bancos y reguladores recomiendan que la cuota no supere el 30–35 % de los ingresos netos. En horas: 48–56 horas de un mes de 160. Si tu resultado es mayor, baja el capital, alarga el plazo o aumenta la entrada.</p>'],
    ],
    table: T(['Préstamo', 'Plazo y tipo', 'Cuota mensual', 'Horas al mes'], [['150.000 € (España)', '30 años, 3,2 %', '649 €', '54 h a 12 €/h'], ['250.000 € (España)', '30 años, 3,2 %', '1.081 €', '90 h a 12 €/h'], ['1.500.000 MXN (México)', '20 años, 10,5 %', '14.975 MXN', '158 h a 95 MXN/h'], ['3.000.000 MXN (México)', '20 años, 10,5 %', '29.950 MXN', '315 h a 95 MXN/h']]),
    faqs: [
      ['¿Cómo se calcula la cuota de una hipoteca?', 'Con la fórmula francesa: capital × tipo mensual ÷ (1 − (1 + tipo mensual)^−meses).'],
      ['¿Qué porcentaje del sueldo debe ir a la hipoteca?', 'Como máximo el 30–35 % de los ingresos netos, unas 50–55 horas de trabajo al mes.'],
      ['¿Qué tipos de interés hay en 2026?', 'En España las hipotecas fijas rondan el 2,8–3,5 % TIN; en México los créditos hipotecarios bancarios están entre el 9,5 % y el 12 %.'],
    ],
  },
  'guides/calculadora-salario-hora-2026-latam': {
    lang: 'es',
    name: 'Calculadora de salario por hora 2026',
    title: 'Calculadora de salario por hora 2026: sueldo mensual a hora | Worth',
    description: 'Convierte tu sueldo mensual o anual en salario por hora en México, Argentina, Colombia, Chile y España. Fórmulas, horas legales por país y tabla 2026.',
    intro: 'Pasa de sueldo mensual a salario por hora con las horas de jornada de tu país y usa el resultado para medir cualquier compra en horas.',
    keywords: ['calculadora salario por hora', 'sueldo mensual a hora', 'salario por hora 2026'],
    sections: [
      ['Fórmula', '<p><strong>Salario por hora = sueldo mensual neto ÷ horas trabajadas al mes.</strong> Las horas mensuales dependen de la jornada legal: 48 h semanales en México (208 h/mes), 45 h en Chile y Colombia en 2026 (195 h), 40 h en España (173 h). Un sueldo neto de 15.000 MXN entre 208 horas son 72 MXN por hora.</p>'],
      ['Salario mínimo 2026 por hora', '<p>México: 315,04 MXN diarios, unos 39 MXN/hora. España: 1.184 € en 14 pagas, unos 8,87 €/hora. Colombia: 1.750.905 COP, unos 8.980 COP/hora. Chile: 529.000 CLP, unos 2.710 CLP/hora. Usa el neto real, no el bruto, para medir compras.</p>'],
      ['Para qué sirve el número', '<p>Cualquier precio dividido entre tu salario por hora se convierte en horas de trabajo. Un teléfono de 12.000 MXN a 72 MXN/hora son 167 horas: un mes entero. La calculadora de arriba hace esa división al instante.</p>'],
    ],
    table: T(['País', 'Jornada legal', 'Sueldo neto ejemplo', 'Por hora'], [['México', '48 h/semana (208 h/mes)', '15.000 MXN', '72 MXN'], ['Colombia', '44 h/semana (191 h/mes)', '2.500.000 COP', '13.090 COP'], ['Chile', '44 h/semana (191 h/mes)', '700.000 CLP', '3.665 CLP'], ['Argentina', '48 h/semana (208 h/mes)', '900.000 ARS', '4.327 ARS'], ['España', '40 h/semana (173 h/mes)', '1.600 €', '9,25 €']]),
    faqs: [
      ['¿Cómo calculo mi salario por hora?', 'Divide el sueldo mensual neto entre las horas que trabajas al mes; para una jornada de 40 horas son 173,33 horas.'],
      ['¿Uso el sueldo bruto o el neto?', 'El neto: es el dinero que realmente llega a tu cuenta y el que gastas.'],
      ['¿Cuántas horas al mes tiene una jornada de 48 horas?', 'Aproximadamente 208 horas (48 × 52 ÷ 12).'],
    ],
  },
  'guides/stundenlohn-rechner-deutschland-2026': {
    lang: 'de',
    name: 'Stundenlohn-Rechner 2026: Gehalt in Stundenlohn umrechnen',
    title: 'Stundenlohn-Rechner 2026: Brutto- und Nettogehalt pro Stunde | Worth',
    description: 'Rechne Monats- oder Jahresgehalt in den Stundenlohn um, brutto und netto. Formel, Mindestlohn 2026 (13,90 €), Tabelle nach Wochenstunden und Kaufpreise in Arbeitsstunden.',
    intro: 'Vom Monatsgehalt zum Netto-Stundenlohn, und dann jeden Preis in Arbeitsstunden umrechnen.',
    keywords: ['stundenlohn rechner', 'gehalt in stundenlohn umrechnen', 'stundenlohn 2026'],
    sections: [
      ['Die Formel', '<p><strong>Stundenlohn = Monatsgehalt × 3 ÷ 13 ÷ Wochenstunden.</strong> Der Faktor 13 ÷ 3 = 4,33 ist die durchschnittliche Zahl der Wochen pro Monat. 3.500 € brutto bei 40 Stunden ergeben 20,19 € brutto pro Stunde. Netto (Steuerklasse I, ohne Kirchensteuer) bleiben etwa 2.330 €, also rund 13,45 € pro Stunde.</p>'],
      ['Mindestlohn und Vergleichswerte 2026', '<p>Der gesetzliche Mindestlohn steigt zum 1. Januar 2026 auf 13,90 € und 2027 auf 14,60 €. Der mittlere Bruttostundenlohn für Vollzeit lag zuletzt bei rund 24 €. Für Kaufentscheidungen zählt aber der Nettostundenlohn.</p>'],
      ['Preise in Arbeitsstunden', '<p>Teile jeden Preis durch den Nettostundenlohn. Ein 1.200-€-Laptop bei 13,45 € netto kostet 89 Arbeitsstunden, mehr als zwei Wochen. Der Rechner oben macht genau diese Division.</p>'],
    ],
    table: T(['Bruttogehalt/Monat', 'Wochenstunden', 'Brutto/Stunde', 'Netto/Stunde (StKl. I, ca.)'], [['2.400 €', '40', '13,85 €', '9,90 €'], ['3.500 €', '40', '20,19 €', '13,45 €'], ['4.500 €', '40', '25,96 €', '16,50 €'], ['3.500 €', '30', '26,92 €', '18,00 €']]),
    faqs: [
      ['Wie rechne ich mein Gehalt in Stundenlohn um?', 'Monatsgehalt mal 3, geteilt durch 13, geteilt durch die Wochenstunden.'],
      ['Wie hoch ist der Mindestlohn 2026?', '13,90 € brutto pro Stunde ab 1. Januar 2026.'],
      ['Brutto oder netto rechnen?', 'Für Kaufentscheidungen netto; das ist das Geld, das tatsächlich auf dem Konto landet.'],
    ],
  },
  'guides/calculateur-salaire-horaire-france-2026': {
    lang: 'fr',
    name: 'Calculateur de salaire horaire 2026',
    title: 'Calculateur salaire horaire 2026 : mensuel en taux horaire net | Worth',
    description: 'Convertissez un salaire mensuel ou annuel en taux horaire brut et net. Formule 151,67 h, SMIC 2026, tableau par salaire et prix exprimés en heures de travail.',
    intro: 'Du salaire mensuel au taux horaire net, puis chaque achat converti en heures de travail.',
    keywords: ['calculateur salaire horaire', 'salaire mensuel en taux horaire', 'smic horaire 2026'],
    sections: [
      ['La formule', '<p><strong>Taux horaire = salaire mensuel ÷ 151,67.</strong> Pour 35 heures par semaine, le mois compte 151,67 heures (35 × 52 ÷ 12). Un salaire de 2 600 € brut donne 17,14 € brut de l&rsquo;heure ; le net, environ 78 % du brut dans le privé, fait 13,40 € de l&rsquo;heure.</p>'],
      ['SMIC et repères 2026', '<p>Le SMIC horaire brut est de 11,88 € (1 801,80 € mensuel brut, environ 1 426 € net). Le salaire net médian en France est d&rsquo;environ 2 100 € par mois, soit 13,85 € net de l&rsquo;heure.</p>'],
      ['Un prix en heures de travail', '<p>Divisez le prix par votre taux horaire net. Un smartphone à 1 000 € à 13,40 € net de l&rsquo;heure coûte 75 heures, soit deux semaines de travail. Le calculateur ci-dessus fait cette division.</p>'],
    ],
    table: T(['Salaire mensuel brut', 'Taux horaire brut (151,67 h)', 'Net estimé/heure'], [['1 801,80 € (SMIC)', '11,88 €', '9,40 €'], ['2 600 €', '17,14 €', '13,40 €'], ['3 500 €', '23,08 €', '18,00 €'], ['5 000 €', '32,97 €', '25,70 €']]),
    faqs: [
      ['Comment calculer son taux horaire ?', 'Divisez le salaire mensuel par 151,67 pour un temps plein à 35 heures.'],
      ['Quel est le SMIC horaire en 2026 ?', '11,88 € brut, soit environ 9,40 € net.'],
      ['Faut-il utiliser le brut ou le net ?', 'Le net pour décider d&rsquo;un achat : c&rsquo;est l&rsquo;argent réellement disponible.'],
    ],
  },
  'guides/калькулятор-зарплаты-час-россия-2026': {
    lang: 'ru',
    name: 'Калькулятор зарплаты в час 2026',
    title: 'Калькулятор зарплаты в час 2026: оклад в почасовую ставку | Worth',
    description: 'Переведите месячный оклад в ставку за час по производственному календарю 2026 года. Формула, МРОТ 2026 (27 093 ₽), таблица и цены в часах работы.',
    intro: 'Из месячного оклада в чистую ставку за час, а затем любая покупка в часах работы.',
    keywords: ['калькулятор зарплаты в час', 'оклад в час', 'мрот 2026'],
    sections: [
      ['Формула', '<p><strong>Ставка в час = оклад ÷ норма часов в месяце.</strong> Средняя месячная норма при 40-часовой неделе в 2026 году около 164,5 часа. Оклад 80 000 ₽ до вычета НДФЛ даёт 486 ₽ в час; после 13 % НДФЛ остаётся 69 600 ₽, то есть 423 ₽ в час.</p>'],
      ['МРОТ и ориентиры 2026', '<p>МРОТ с 1 января 2026 года составляет 27 093 ₽ в месяц, около 165 ₽ в час. Медианная зарплата по стране порядка 65 000 ₽ до налога, примерно 344 ₽ в час на руки.</p>'],
      ['Цена в часах работы', '<p>Разделите цену на чистую ставку. Смартфон за 60 000 ₽ при 423 ₽ в час стоит 142 часа, почти месяц работы. Калькулятор выше делает это деление мгновенно.</p>'],
    ],
    table: T(['Оклад до НДФЛ', 'На руки (13 %)', 'Ставка в час (164,5 ч)'], [['27 093 ₽ (МРОТ)', '23 571 ₽', '143 ₽'], ['65 000 ₽', '56 550 ₽', '344 ₽'], ['80 000 ₽', '69 600 ₽', '423 ₽'], ['150 000 ₽', '130 500 ₽', '793 ₽']]),
    faqs: [
      ['Как перевести оклад в ставку за час?', 'Разделите оклад на норму рабочих часов в месяце; в среднем в 2026 году это 164,5 часа.'],
      ['Какой МРОТ в 2026 году?', '27 093 ₽ в месяц.'],
      ['Считать до налога или после?', 'После НДФЛ: для решений о покупках важны деньги, которые реально приходят на карту.'],
    ],
  },
  'guides/时薪计算器-中国-2026': {
    lang: 'zh',
    name: '时薪计算器 2026：月薪换算每小时工资',
    title: '时薪计算器 2026：月薪换算时薪与工作小时 | Worth',
    description: '按 21.75 天法定折算把月薪换成时薪，含各地 2026 年最低工资、税后估算表，以及把任何价格换算成工作小时的方法。',
    intro: '把月薪换算成税后时薪，再把每一笔消费换算成需要工作的小时数。',
    keywords: ['时薪计算器', '月薪换算时薪', '最低工资 2026'],
    sections: [
      ['换算公式', '<p><strong>时薪 = 月薪 ÷ 21.75 ÷ 8。</strong>21.75 是法定月计薪天数，标准工时每月约 174 小时。月薪 10,000 元的税前时薪约 57.5 元；扣除社保公积金和个税后到手约 8,000 元，税后时薪约 46 元。</p>'],
      ['2026 年最低工资参考', '<p>上海月最低工资 2,740 元（时薪约 15.7 元），北京 2,540 元，深圳 2,520 元。全国城镇非私营单位平均月薪约 10,000 元，私营单位约 6,000 元。用来衡量消费时请使用税后到手数字。</p>'],
      ['把价格换算成小时', '<p>价格 ÷ 税后时薪 = 需要工作的小时。一部 6,000 元的手机，在时薪 46 元下需要 130 小时，接近一个月的工作量。上方计算器直接完成这个除法。</p>'],
    ],
    table: T(['税前月薪', '税前时薪 (174 h)', '到手估算', '税后时薪'], [['2,740 元（上海最低）', '15.7 元', '2,500 元', '14.4 元'], ['6,000 元', '34.5 元', '5,100 元', '29.3 元'], ['10,000 元', '57.5 元', '8,000 元', '46 元'], ['20,000 元', '115 元', '14,800 元', '85 元']]),
    faqs: [
      ['时薪怎么算？', '月薪 ÷ 21.75 天 ÷ 8 小时。'],
      ['为什么用 21.75 天？', '这是国家规定的月计薪天数：(365 − 104 个休息日) ÷ 12。'],
      ['应该用税前还是税后？', '衡量消费用税后到手工资，那才是真正可以花的钱。'],
    ],
  },
  'guides/時給計算機-日本-2026': {
    lang: 'ja',
    name: '時給計算機 2026：月給・年収を時給に換算',
    title: '時給計算機 2026：月給・年収から手取り時給を計算 | Worth',
    description: '月給や年収を時給に換算する計算式、2026年の最低賃金（全国平均1,121円）、手取り時給の目安表、そして買い物を労働時間に換算する方法。',
    intro: '月給から手取り時給を求め、あらゆる価格を「何時間働けば買えるか」に換算します。',
    keywords: ['時給計算', '月給 時給 換算', '最低賃金 2026'],
    sections: [
      ['計算式', '<p><strong>時給 = 月給 ÷ 月平均所定労働時間。</strong>週40時間なら月およそ173時間（40 × 52 ÷ 12）。月給30万円なら額面時給は約1,734円。社会保険料と税を引いた手取りは約24万円で、手取り時給は約1,390円です。</p>'],
      ['2026年の最低賃金と目安', '<p>2025年10月改定の最低賃金は全国加重平均1,121円、東京1,226円。正社員の平均月給は約33万円（額面時給約1,900円）。買い物の判断には手取り時給を使ってください。</p>'],
      ['価格を労働時間に', '<p>価格 ÷ 手取り時給 = 必要な労働時間。15万円のスマートフォンは手取り時給1,390円なら108時間、ほぼ3週間分の労働です。上の計算機がこの割り算を行います。</p>'],
    ],
    table: T(['額面月給', '額面時給 (173 h)', '手取り目安', '手取り時給'], [['19.4万円（最低賃金相当）', '1,121円', '15.8万円', '913円'], ['25万円', '1,445円', '20.2万円', '1,168円'], ['30万円', '1,734円', '24万円', '1,390円'], ['45万円', '2,601円', '34.5万円', '1,994円']]),
    faqs: [
      ['月給から時給を計算するには？', '月給を月の所定労働時間（週40時間なら約173時間）で割ります。'],
      ['2026年の最低賃金は？', '全国加重平均1,121円、東京都1,226円です。'],
      ['額面と手取りのどちらで計算すべき？', '買い物の判断は手取りで。実際に使えるお金だからです。'],
    ],
  },
  'guides/연봉-시급-계산기-한국-2026': {
    lang: 'ko',
    name: '연봉 시급 계산기 2026',
    title: '연봉 시급 계산기 2026: 연봉·월급을 시급으로 환산 | Worth',
    description: '연봉이나 월급을 시급으로 바꾸는 공식(209시간), 2026년 최저시급 10,320원, 실수령 시급 표, 그리고 물건값을 근무시간으로 환산하는 방법.',
    intro: '연봉을 실수령 시급으로 바꾸고, 모든 지출을 "몇 시간 일해야 하는가"로 환산합니다.',
    keywords: ['연봉 시급 계산기', '월급 시급 환산', '최저시급 2026'],
    sections: [
      ['계산 공식', '<p><strong>시급 = 월급 ÷ 209시간.</strong> 주 40시간에 주휴 8시간을 더해 월 209시간이 법정 기준입니다. 연봉 4,000만 원은 월 333만 원, 세전 시급 약 15,950원. 4대 보험과 소득세를 빼면 실수령 약 292만 원, 실수령 시급 약 13,970원입니다.</p>'],
      ['2026년 최저시급과 기준', '<p>2026년 최저시급은 10,320원, 월 환산 2,156,880원입니다. 임금근로자 중위 월급은 약 300만 원(세전 시급 약 14,350원). 소비 판단에는 실수령 시급을 사용하세요.</p>'],
      ['가격을 근무시간으로', '<p>가격 ÷ 실수령 시급 = 필요한 근무시간. 150만 원짜리 스마트폰은 시급 13,970원 기준 107시간, 거의 3주치 노동입니다. 위 계산기가 이 나눗셈을 바로 해줍니다.</p>'],
    ],
    table: T(['연봉', '세전 시급 (209 h)', '실수령 월급 추정', '실수령 시급'], [['2,588만 원 (최저임금)', '10,320원', '196만 원', '9,380원'], ['3,600만 원', '14,354원', '266만 원', '12,730원'], ['4,000만 원', '15,949원', '292만 원', '13,970원'], ['6,000만 원', '23,923원', '418만 원', '20,000원']]),
    faqs: [
      ['월급을 시급으로 어떻게 계산하나요?', '월급을 209시간으로 나눕니다.'],
      ['왜 209시간인가요?', '주 40시간 근무에 유급 주휴 8시간을 더한 48시간 × 4.345주 ≈ 209시간이기 때문입니다.'],
      ['2026년 최저시급은 얼마인가요?', '10,320원입니다.'],
    ],
  },
  'guides/حاسبة-الراتب-بالساعة-السعودية-2026': {
    lang: 'ar',
    name: 'حاسبة الراتب بالساعة 2026',
    title: 'حاسبة الراتب بالساعة 2026: حوّل راتبك الشهري إلى أجر الساعة | Worth',
    description: 'حوّل الراتب الشهري إلى أجر بالساعة وفق نظام العمل السعودي (48 ساعة أسبوعياً)، مع جدول 2026 والحد الأدنى 4,000 ريال، وطريقة تحويل أي سعر إلى ساعات عمل.',
    intro: 'من الراتب الشهري إلى أجر الساعة الصافي، ثم تحويل كل عملية شراء إلى ساعات عمل.',
    keywords: ['حاسبة الراتب بالساعة', 'تحويل الراتب الشهري الى ساعة', 'أجر الساعة 2026'],
    sections: [
      ['المعادلة', '<p><strong>أجر الساعة = الراتب الشهري ÷ ساعات العمل الشهرية.</strong> بنظام 48 ساعة أسبوعياً يكون الشهر نحو 208 ساعات، وبنظام 40 ساعة نحو 173 ساعة. راتب 8,000 ريال على 208 ساعات يساوي 38.5 ريالاً للساعة. للسعوديين يُخصم 9.75٪ للتأمينات الاجتماعية، فيصبح الصافي نحو 7,220 ريالاً أي 34.7 ريالاً للساعة.</p>'],
      ['مرجعيات 2026', '<p>الحد الأدنى لاحتساب السعودي في نطاقات هو 4,000 ريال شهرياً (نحو 19 ريالاً للساعة على 208 ساعات). متوسط أجور السعوديين في القطاع الخاص يقارب 10,000 ريال. استخدم الصافي الفعلي عند تقييم المشتريات.</p>'],
      ['السعر بالساعات', '<p>اقسم أي سعر على أجر الساعة الصافي. هاتف بـ 4,500 ريال عند 34.7 ريالاً للساعة يكلّف 130 ساعة عمل، أي أكثر من ثلاثة أسابيع. الحاسبة أعلاه تجري هذه القسمة فوراً.</p>'],
    ],
    table: T(['الراتب الشهري', 'أجر الساعة (208 ساعة)', 'الصافي بعد التأمينات 9.75٪', 'أجر الساعة الصافي'], [['4,000 ريال', '19.2 ريال', '3,610 ريال', '17.4 ريال'], ['8,000 ريال', '38.5 ريال', '7,220 ريال', '34.7 ريال'], ['12,000 ريال', '57.7 ريال', '10,830 ريال', '52.1 ريال'], ['20,000 ريال', '96.2 ريال', '18,050 ريال', '86.8 ريال']]),
    faqs: [
      ['كيف أحسب أجر الساعة من الراتب الشهري؟', 'اقسم الراتب على ساعات العمل الشهرية: 208 لنظام 48 ساعة أسبوعياً أو 173 لنظام 40 ساعة.'],
      ['ما الحد الأدنى للأجور في السعودية 2026؟', '4,000 ريال شهرياً لاحتساب الموظف السعودي ضمن نطاقات.'],
      ['هل أستخدم الراتب الإجمالي أم الصافي؟', 'الصافي، لأنه المبلغ الذي يصل فعلياً إلى حسابك.'],
    ],
  },
  'guides/calculadora-horas-trabalho-brasil-2026': {
    lang: 'pt',
    name: 'Calculadora de salário por hora 2026 (Brasil)',
    title: 'Calculadora de salário por hora 2026: salário mensal em valor-hora | Worth',
    description: 'Converta salário mensal em valor por hora pela regra das 220 horas da CLT. Salário mínimo 2026 (R$ 1.621), tabela líquida e preços em horas de trabalho.',
    intro: 'Do salário mensal ao valor-hora líquido, e depois qualquer compra convertida em horas de trabalho.',
    keywords: ['calculadora salário por hora', 'salário mensal valor hora', 'salário mínimo 2026'],
    sections: [
      ['A fórmula da CLT', '<p><strong>Valor-hora = salário mensal ÷ 220.</strong> A jornada de 44 horas semanais equivale a 220 horas mensais pela CLT. Um salário de R$ 3.500 dá R$ 15,91 por hora bruto. Descontando INSS e IRRF, o líquido fica em torno de R$ 3.100, ou R$ 14,09 por hora.</p>'],
      ['Referências 2026', '<p>O salário mínimo de 2026 é R$ 1.621, ou R$ 7,37 por hora. O rendimento médio real do trabalho está perto de R$ 3.500. Para decidir compras, use o valor-hora líquido, não o bruto.</p>'],
      ['Preço em horas', '<p>Divida o preço pelo valor-hora líquido. Um celular de R$ 3.000 a R$ 14,09 por hora custa 213 horas, quase um mês inteiro de trabalho. A calculadora acima faz essa conta na hora.</p>'],
    ],
    table: T(['Salário bruto', 'Valor-hora bruto (220 h)', 'Líquido estimado', 'Valor-hora líquido'], [['R$ 1.621 (mínimo)', 'R$ 7,37', 'R$ 1.500', 'R$ 6,82'], ['R$ 3.500', 'R$ 15,91', 'R$ 3.100', 'R$ 14,09'], ['R$ 6.000', 'R$ 27,27', 'R$ 4.900', 'R$ 22,27'], ['R$ 10.000', 'R$ 45,45', 'R$ 7.600', 'R$ 34,55']]),
    faqs: [
      ['Como calcular o valor da hora de trabalho?', 'Divida o salário mensal por 220 para jornada de 44 horas semanais, ou por 200 para 40 horas.'],
      ['Qual o salário mínimo em 2026?', 'R$ 1.621 por mês, R$ 7,37 por hora.'],
      ['Uso o salário bruto ou líquido?', 'O líquido, que é o dinheiro que efetivamente entra na conta.'],
    ],
  },
  'guides/how-much-youtubers-make-2026-shocking-truth': {
    name: 'How Much YouTubers Really Make in 2026',
    title: 'How Much Do YouTubers Make in 2026? Real Numbers by Size | Worth',
    description: 'Realistic 2026 YouTube income by channel size, from 1,000 to 10 million subscribers, with RPMs, sponsorship rates and the hourly pay most creators actually earn.',
    intro: 'Real income ranges by channel size, and what they work out to per hour of production.',
    keywords: ['how much do youtubers make', 'youtube income 2026', 'youtuber salary'],
    sections: [
      ['The distribution is brutal', '<p>About 97% of YouTube channels never reach the 1,000-subscriber monetization threshold. Of those that do, most earn under $500 a month from ads. Income scales with views, RPM and, above all, off-platform revenue.</p>'],
      ['AdSense by channel size', '<p><strong>Monthly AdSense ≈ monthly views ÷ 1,000 × RPM.</strong> A 100,000-subscriber channel typically gets 500,000–2 million views a month; at a $4 RPM that is $2,000–$8,000. Finance, tech and business channels earn 3–5× that per view; gaming and entertainment earn less.</p>'],
      ['Sponsorships change everything', '<p>Brand deals pay roughly $20–$50 per 1,000 expected views, five to ten times AdSense. A mid-size channel with two sponsors a month can double or triple its income. Merch, courses, and memberships add another layer for creators with loyal audiences.</p>'],
      ['Per hour', '<p>Divide monthly income by production hours. A creator earning $4,000 who spends 120 hours a month makes $33 per hour, decent but not a lottery ticket. Below 50,000 subscribers the typical figure is under $10 per hour. Run your own numbers with the calculator above.</p>'],
    ],
    table: T(['Subscribers', 'Typical monthly views', 'AdSense at $4 RPM', 'With sponsors', 'Hourly at 120 h/month'], [['1,000–10,000', '20,000', '$80', '$150', '$1.25'], ['50,000', '300,000', '$1,200', '$3,000', '$25'], ['100,000', '1,000,000', '$4,000', '$10,000', '$83'], ['1,000,000', '8,000,000', '$32,000', '$90,000', '$750'], ['10,000,000', '60,000,000', '$240,000', '$700,000+', '$5,800']]),
    faqs: [
      ['How much does a YouTuber with 100k subscribers make?', 'Usually $2,000–$10,000 a month combining ads and sponsorships, depending on niche and upload rate.'],
      ['How much does YouTube pay per view?', 'About $0.001–$0.005 per view after YouTube&rsquo;s cut for most niches; up to $0.02 in finance and software.'],
      ['Do most YouTubers make money?', 'No. The majority never reach monetization, and most monetized channels earn a few hundred dollars a month.'],
    ],
  },
  'guides/cost-of-time-elon-musk-jeff-bezos-2026': {
    name: 'Cost of Time: Musk, Bezos, and You in 2026',
    title: 'Cost of Time 2026: What an Hour Is Worth to Musk, Bezos and You | Worth',
    description: 'What an hour is worth to the world\u2019s richest people versus a median worker in 2026, how those figures are calculated, and why your own number matters more.',
    intro: 'A side-by-side of what an hour is worth at the top of the wealth distribution and at the median, with the math behind each figure.',
    keywords: ['elon musk per hour', 'jeff bezos earnings per hour', 'cost of time billionaires'],
    sections: [
      ['How billionaire hourly figures are built', '<p><strong>Per hour = change in net worth over a period ÷ hours in that period.</strong> Musk&rsquo;s net worth rose roughly $200 billion in 2024: about $22.8 million per hour. Bezos gained around $60 billion: $6.8 million per hour. Both are paper gains from share prices; in down years the same math is negative.</p>'],
      ['The median worker', '<p>US median hourly earnings for full-time workers are about $30 gross, $23–$25 after tax. That is the number every price in your life actually divides into. A $1,200 laptop is 50 working hours at $24; it is 0.19 seconds of Musk&rsquo;s 2024 rate.</p>'],
      ['Why the comparison is misleading, and still useful', '<p>Wealth gains are not income; billionaires cannot spend share price without selling and paying tax. But the comparison shows what &ldquo;cost of time&rdquo; means: the same object costs radically different amounts of life depending on who is buying. The number that should change your behavior is yours.</p>'],
      ['Compute your own', '<p>Take-home pay ÷ hours worked = your hourly value. Include commuting and unpaid overtime for a true rate. Then use the calculator above on your next non-trivial purchase.</p>'],
    ],
    table: T(['Person', 'Basis', 'Per hour', '$1,200 laptop costs'], [['Elon Musk', '+$200B net worth, 2024', '$22.8M', '0.19 s'], ['Jeff Bezos', '+$60B net worth, 2024', '$6.8M', '0.6 s'], ['Top 1% household', '$600k income', '$290 gross', '4.1 h'], ['Median US worker', '$30/h gross, $24 net', '$24 net', '50 h']]),
    faqs: [
      ['How much does Elon Musk make per hour?', 'Roughly $22.8 million per hour based on 2024 net worth growth; it is unrealized stock value, not pay.'],
      ['How much does Jeff Bezos make per hour?', 'About $6.8 million per hour on the same basis for 2024.'],
      ['How do I calculate what my time is worth?', 'Divide take-home pay by total hours worked, including commute if you want a true rate.'],
    ],
  },
};

export const extraRoutes = Object.keys(pages);
